### ISSUE TITLE
Pipeline creation fails with "Internal Failure"

### ISSUE THREAD

**Issue by FelixRelli** [aws-cloudformation/cloudformation-cli#1018]
Hi, 

Not sure if the right place here, but when creating a CodePipeline and the secretsmanager:GetSecretValue is pointing to a secret that does not exist in the account, cloudformation just fails with "Internal Failure" for the Pipeline without giving any hint on what the issue really is.

**Comment by mircealam** [comment]
This is not the right place. Please verify if there is an issue here and if not please open one: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap

Also, when reporting the issue it helps if you can provide a bit more details to help replicate the issue (e.g. a minimal template that helps reproduce the issue can immensely help)
