### ISSUE TITLE
AWS CloudControl schema breaking change policy

### ISSUE THREAD

**Issue by bagajjal** [aws-cloudformation/cloudformation-cli#1036]
* Is the removal of a property from an existing resource type considered a breaking change?
    * If so, what is the protocol for notifying users about such modifications?
    * If not, how can customers ensure the compatibility of their client applications in the event of schema alterations? Is there a mechanism to receive responses based on the existing schema rather than the current one? Typically, this is achieved through an API versioning approach, but I do not see AWS CloudControl API accepting an api-version input parameter. What guidance does AWS provide regarding this?

Given that AWS does not maintain a Github repository for AWS CloudControl schema, I'm looking to Pulumi for insights into property removal within a specific resource type. According to pulumi (https://github.com/pulumi/pulumi-aws-native/pull/1124), there have been instances of property removals for certain resources.

![image](https://github.com/aws-cloudformation/cloudformation-cli/assets/23668037/4154b0c1-1103-48d3-b4b8-880d5840b650)

**Comment by bagajjal** [comment]
@mircealam, can you please look into this issue.

**Comment by benbridts** [comment]
This probably does not completely answer your question, but you can mark properties as deprecated in the resource schema:

https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html#schema-properties-deprecatedproperties

> *deprecatedProperties*
>
> Resource properties that have been deprecated by the underlying service provider. These properties are still accepted in create and update operations. However they may be ignored, or converted to a consistent model on application. Deprecated properties are not guaranteed to be returned by read operations.
>
> Type: List of JSON pointers

**Comment by bagajjal** [comment]
@benbridts, I appreciate your response. Regrettably, it doesn't provide the information I'm seeking.

@mircealam, whenever you have a moment, could you kindly provide answers to my questions? Thank you.

**Comment by bagajjal** [comment]
@mircealam, ping.

**Comment by bagajjal** [comment]
@mircealam,

Pulumi reads the cloud formation schema from https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip and then stores the cloud formation schema in Pulumi repository. Looking at the Pulumi history, the "id" is a deprecated property.

![image](https://github.com/aws-cloudformation/cloudformation-cli/assets/23668037/9d3ff586-bdd7-4377-b603-d024062f6041)

Few follow-up questions,
1. The addition of new properties is not considered as a breaking change? Even in this case, the contract between client and AWS service changes so ideally it should be treated as a breaking change?

2. In the event of deprecating properties, is there a way to get the AWS response in the previous schema that has the deprecated properties? AWS CloudControl API doesn't take in API version so I'm not sure.

3. What is the process for deprecating properties for a resource type?
