### ISSUE TITLE
Validate returned resources with resource schema

### ISSUE THREAD

**Issue by jotompki** [aws-cloudformation/cloudformation-cli#108]
In contract tests, whenever resources are returned by handlers, verify that the returned resource is compliant with the resource schema for said resource.

**Comment by jotompki** [comment]
We should also validate that writeOnly properties are not returned from handlers in the same validation.

**Comment by anshikg** [comment]
As far as I know we read after the resource is created to check if the resource created is valid. Also, we are checking for write only properties. Please let me know if there a specific test case we want to test here.

**Comment by anshikg** [comment]
Closing this issue, as I see no follow up items. Feel free to open it if there is something I am missing.
