### ISSUE TITLE
Fast sanely when credentials are invalid

### ISSUE THREAD

**Issue by johnttompkins** [aws-cloudformation/cloudformation-cli#147]
On commands that require interaction with AWS (package and submit), we should fast fail and report some error to the user if their credentials are invalid. Currently the user would have to look in the logs to see this result. A function that checks credentials could be added before these command execute their main portions, and this function could inform the user of no credentials or bad credentials.

**Comment by PatMyron** [comment]
[`botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the ListExports operation: The security token included in the request is expired`](https://github.com/aws-cloudformation/cloudformation-cli/pull/411)
