### ISSUE TITLE
`Init` command should cleanup previous codegen runs

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#151]
When playing with the `init` wizard, I noticed that if I re-run `init` in the same repo and change my resource type name, the generated sources from a prior execution are left in place (not overwritten or removed) which can lead to broken build.

To repro;
```
uluru-cli init
a::b::c
mvn package
```

Builds OK.

```
uluru-cli init
My::Actual::Resource
mvn package
```

Fails, as the src from a/b/c is left in the repo. Not a biggie, just a usability enhancement.

**Comment by PatMyron** [comment]
This is probably better solved by just implementing https://github.com/aws-cloudformation/cloudformation-cli/issues/272
