### ISSUE TITLE
Support disconnected development

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#228]
Currently, at least the `generate` command fails when operating disconnected. Partly because of JSON Schema fetch issues. Perhaps we can treat these errors as `WARN` level and allow a best-effort codegen to work when disconnected? Or, once successful a local cache can be used in favour of live fetch of remote assets on every build.

**Comment by PatMyron** [comment]
> Or, once successful a local cache can be used in favour of live fetch of remote assets on every build.

[`requests_cache`](https://pypi.org/project/requests-cache/) works well if we're using `requests`

**Comment by wbingli** [comment]
Quick search, it can be fixed use local file for schema reference, see https://github.com/Julian/jsonschema/issues/98

**Comment by wbingli** [comment]
Fixed under #436
