### ISSUE TITLE
Bootstrap provider repositories with schema tests

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#253]
To make development of initial schemas easier, we could emit some schema test payloads against the sample, to demonstrate a process for validating that not only is your provider schema *valid* but also correct. 

This will help schema authors prove that their schemas are validating the correct resource definitions. We can also encourage use of https://jsonschemavalidator.net for dynamic testing, but some unit tests of schema are also a valid improvement, and not currently impacting code coverage (though it should, ideally).

**Comment by PatMyron** [comment]
While still not impacting code coverage, the [contract tests](https://github.com/aws-cloudformation/cloudformation-cli/tree/master/src/rpdk/core/contract/) should cover this when using [resource generation](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/resource_generator.py)
