### ISSUE TITLE
cfn-cli should support the end-to-end API flow

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#285]
Currently, after `cfn-cli submit` a user must jump over to the aws-cli to complete the end-to-end process for registering a type. Certain API calls are not supported in the RPDK and it would be useful if the user could stay within cfn-cli for the full development cycle;

1. `cfn-cli submit` kicks off a type registration
2. `aws cloudformation describe-type-registration` now must be called periodically to check if a type registration is successful.
3. `aws cloudformation set-type-default-version` now must be called to finalise registration with CloudFormation

It would be great if the `cfn-cli submit` command became an interactive process which periodically invokes the `describe-type-registration` API until it sees a terminal outcome, and can emit events to the console to show progress status.

Then, a final `y/n` prompt to allow a user to have the `cfn-cli` call `set-type-default-version` on their behalf.

**Comment by PatMyron** [comment]
`cfn submit --set-default` added in https://github.com/aws-cloudformation/cloudformation-cli/pull/328/
