### ISSUE TITLE
Support `package` for cfn-cli

### ISSUE THREAD

**Issue by wbingli** [aws-cloudformation/cloudformation-cli#286]
For a resource development CI/CD pipeline,  customer need to make a RPDK package only during build time. 

Currently `cf-cli submit --dry-run` will generate a package without submit. But it would be great to have `package`  or `build` command to do only build and package to generate artifact.

**Comment by richardhboyd** [comment]
`submit —dry-run` implies that it will also validate if I have the appropriate permissions to execute the submission. I believe `package` more accurately reflects what the cfn CLI is actually doing.

**Comment by ikben** [comment]
This is very similar to https://github.com/aws-cloudformation/cloudformation-cli/issues/368

**Comment by richardhboyd** [comment]
I think the difference between the two is the name of the command. `cfn submit --dry-run` makes a user think it will validate that a bucket exists with the right permissions and the current user has sufficient privileges to perform a submit. `package` is an entirely local operation that should be able to execute even without IAM credentials.
