### ISSUE TITLE
Update resource blob generation smarts

### ISSUE THREAD

**Issue by tobywf** [aws-cloudformation/cloudformation-cli#287]
Generating a resource blob for update is much more tricky than create. It requires not generating and/or merging in create-only and read-only properties in a deep merge manner, and may need to become even more schema aware, such as respecting `oneOf` (i.e. not merging two keys where `oneOf` applies).

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/cloudformation-cli/issues/118
