### ISSUE TITLE
schema_merge does not quite correctly validate merged schemas correctly

### ISSUE THREAD

**Issue by aygold92** [aws-cloudformation/cloudformation-cli#333]
In the schema flattener, when there is a combiner (`anyOf`, `allOf`, or `oneOf`), we combine the schemas together in order to make one unified schema.

We currently validate that multiple $refs cant be declared and that multiple types cannot be declared.  However, this misses a few possibilites:
1. both type and $ref are defined.  type can be defined as string but $ref to an object, and we will accept it.  So this schema is valid when it should NOT be:
```
{
       "typeName": "AWS::Valid::TypeName",
        "definitions": {"obj": {"properties": {"Foo": {"type": "object"}}}},
        "properties": {
            "p": {anyOf: [
                     {"type": "string"}, 
                     {"$ref": "#definitions/obj"}
              ]}
        }
}
```
2. Multiple refs go to compatible types.  they can declare different properties, or the same type for the same property.  Actually, these refs need to be merged as well.
So this schema is invalid, when it should be:
```
{
        "typeName": "AWS::Valid::TypeName",
        "definitions": {
            "obj": {"properties": {"a": {"type": "object"}}},
            "obj2": {"properties": {"a": {"type": "object"}}}
        },
        "properties": {
            "p": {
                "allOf": [
                    {"$ref": "#/definitions/obj"},
                    {"$ref": "#/definitions/obj2"}
                ]
            }
        },
    }
```

Oddly enough, it seems the solution is to completely unflatten the schemas in order to validate the constraints properly, and then flatten them back again.

**Comment by ammokhov** [comment]
closing as being tracked in #242
