### ISSUE TITLE
Repository should be renamed to reflect launch naming

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#346]
Our working title `aws-cloudformation-rpdk` should be updated to `aws-cloudformation-cli`. GitHub will handle the repository rename cleanly so this should be minimally impactful.

**Comment by tobywf** [comment]
If the organization is already named "aws-cloudformation", can we just name it "cloudformation-cli" to match the name in PyPI?

**Comment by rjlohan** [comment]
Yes that works for me. 👌🏼

**Comment by tobywf** [comment]
sounds good, we'll do this this week. i think you're right that it'll be unproblematic, but do need to check the CI will handle this equally gracefully.

**Comment by jotompki** [comment]
https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by jotompki** [comment]
Looks like it'll handle redirects so shouldn't be too much of a change. Might have to update readmes is the biggest thing. The CI should work but will be good to follow up and update it once the name change is done.

**Comment by jotompki** [comment]
https://github.com/aws-cloudformation/cloudformation-cli/blame/master/README.rst#L96-L98 need to update this

**Comment by tobywf** [comment]
keeping open for cleanup
