### ISSUE TITLE
Contract tests: catch primary identifier change during update

### ISSUE THREAD

**Issue by tobywf** [aws-cloudformation/cloudformation-cli#361]
I don't think primary identifiers/physical resource IDs can be changed during UPDATE, so we should test for this. Maybe additional validation can be added to the resource schema validation to ensure the primary identifier is marked create only.

**Comment by rjlohan** [comment]
Definitely `primaryIdentifier` should require the same setting in `createOnlyProperties` as it can *not* be changed on `Update`.

`readonlyProperties` is an additional semantic setting which would be present if the `primaryIdentifier` is *not* user-defined.
