### ISSUE TITLE
There is no cfn build command

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cloudformation-cli#368]
This might be an issue that is specific to the python plugin with docker.

When running `cfn test` / ` sam local start-lambda`, `sam` mounts the `build` directory to execute the code:
```
Starting the Local Lambda Service. You can now invoke your Lambda Functions defined in your template through the endpoint.
2019-12-12 18:00:59  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
Invoking cloudar_ec2_keypair.handlers.test_entrypoint (python3.7)

Fetching lambci/lambda:python3.7 Docker container image......
Mounting /Users/ben/src/client/cloudar/cloudformation-samples/resource_providers/cloudar_ec2_keypair/build as /var/task:ro,delegated inside runtime container
START RequestId: 73f3f520-3aa4-1988-cd6d-37b9276b09a0 Version: $LATEST
```

The only way I have found to actually get the right code in the build directory (besides copy-pasting it in myself) is to run `cfn submit`. When I am developing my type I'd like to test before I submit. 

An `cfn build` command could fix this. Even better would be that the `cfn test` would do the build and `sam local start-lambda` on its own.

**Comment by rjlohan** [comment]
Have you tried `cfn submit --dry-run`? That might solve.

**Comment by ikben** [comment]
I had not and it does solve it!

**Comment by rjlohan** [comment]
> I had not and it does solve it!

Cool, well this issue can now be 'put that info in the docs' 😄
