### ISSUE TITLE
Internal Error During cfn submit

### ISSUE THREAD

**Issue by james-cooke1** [aws-cloudformation/cloudformation-cli#371]
When running the cfn submit command I get deployment failed message with an internal error, attaching [rpdk.log](https://github.com/aws-cloudformation/cloudformation-cli/files/3975303/rpdk.log) let me know if any additional info is needed.

**Comment by jotompki** [comment]
Hi could you provide the region that you submitted in? Will make it a bit easier for us to track down the failure

**Comment by jotompki** [comment]
Was able to track down the registration. It seems as if your deployment package was over our size limits. In the future the error messaging around this will be clearer. As a way to test, simply try creating a lambda function in your account with the source. If able, you should not see the same error registering a resource type.
