### ISSUE TITLE
`cfn submit --set-default` isn't correctly defaulting to true

### ISSUE THREAD

**Issue by stilvoid** [aws-cloudformation/cloudformation-cli#377]
In `submit.py`, line 35 it looks as though `--set-default` is supposed to default to true. When I submit resources, the default version is not updated unless I specify `--set-default` explicitly.

**Comment by ikben** [comment]
@stilvoid do you mean the 'store_true' action? That means that it should make the value True if the switch is used, and it makes the default False. See https://docs.python.org/3/library/argparse.html#name-or-flags for more information

**Comment by jotompki** [comment]
yeah, so the default value of --set-default is false if not provided, as @ikben mentions, `store_true` just stores the value as true if you include the flag.

**Comment by stilvoid** [comment]
Ah yes ok, so the intended default behaviour is not to make it default? It could be nice if `cfn submit` warned you about it :)

**Comment by jotompki** [comment]
Here's the current description of the command: 
```
cfn submit --help
usage: cfn submit [-h] [-v] [--dry-run] [--endpoint-url ENDPOINT_URL]
                  [--region REGION] [--set-default]
                  [--role-arn ROLE_ARN | --no-role]

This sub command uploads the resource type to CloudFormation. Projects can be
created via the 'init' sub command.

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Increase the output verbosity. Can be specified
                        multiple times.
  --dry-run             Package the project, but do not submit.
  --endpoint-url ENDPOINT_URL
                        CloudFormation endpoint to use.
  --region REGION       AWS Region to submit the resource type.
  --set-default         If registration is successful, set submitted version
                        to the default.
  --role-arn ROLE_ARN   Role ARN that CloudFormation will use when invoking
                        handlers.
  --no-role             Register the type without an explicit execution role
                        (Will not be able to invoke AWS APIs).
```
Do you think additional info should be added here?

**Comment by tobywf** [comment]
> Ah yes ok, so the intended default behaviour is not to make it default? It could be nice if `cfn submit` warned you about it :)

for some context, `--set-default` is because it didn't used to set the default, and we didn't want to change this behaviour. i'm not sure if any automated deployment is using `cfn submit` already, but a change like this would require a bit of a version bump and a warning in the changelog at the very least. (in hindsight, it would've been super useful to always do this and have the automated case use `--no-set-default` or something)
