### ISSUE TITLE
`cfn submit --role-arn` for CloudFormationManagedUploadInfrastructure stack

### ISSUE THREAD

**Issue by sayboras** [aws-cloudformation/cloudformation-cli#379]
The stack CloudFormationManagedUploadInfrastructure was not created by the role specified by `--role-arn` option.

Additionally, it would be nice if this stack policy can support permission boundary as well.

**Comment by jotompki** [comment]
Hi could you expand a bit more on this? The  --role-arn refers to the execution role used when the resource handler provisions resources in your account, so whenever you create the resource type you registered in a CloudFormation stack, CloudFormation is only able to perform the actions allowed in that role. This is not the role that is used when creating the CloudFormationManagedUploadInfrastructure stack. Currently there is no way to pass in a role to use when creating that stack.

**Comment by sayboras** [comment]
@jotompki understand that CloudFormationManagedUploadInfrastructure is not created by `--role-arn` as per current design. However, from consumer's perspective, when I run the command `cfn submit --role-arn`, I would expect all the stacks created by this command `must` be provisioned by this role. This will help with permission control/grant.

**Comment by tobywf** [comment]
If you need to use a specific role, please see [Using an IAM Role in the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html).
