### ISSUE TITLE
Javascript language plugin

### ISSUE THREAD

**Issue by eduardomourar** [aws-cloudformation/cloudformation-cli#397]
Is there a plan to have Javascript/Typescript language plugin supported?

**Comment by rjlohan** [comment]
We don't yet have this on the roadmap, but would welcome any attempts to produce one for the community.

**Comment by eduardomourar** [comment]
I have created a repo to start working in the Typescript plugin: https://github.com/eduardomourar/cloudformation-cli-typescript-plugin

**Comment by eduardomourar** [comment]
First pre-release version available [here](https://github.com/eduardomourar/cloudformation-cli-typescript-plugin/releases/tag/v0.1.0) and sample project [here](https://github.com/brianterry/unicorn-maker/pull/5).

**Comment by eduardomourar** [comment]
We have now a repository with multiple resource providers that are being implemented in TypeScript: https://github.com/org-formation/aws-resource-providers

**Comment by rjlohan** [comment]
> We have now a repository with multiple resource providers that are being implemented in TypeScript: https://github.com/org-formation/aws-resource-providers

Awesome!!

**Comment by anshikg** [comment]
Closing this issue. There is no outstanding issue here. Feel free to reopen this issue if I have missed something
