### ISSUE TITLE
Avoid override Makefile when run cfn generate 

### ISSUE THREAD

**Issue by sayboras** [aws-cloudformation/cloudformation-cli#402]
Currently, `cfn generate` will override the Makefile as well. It's not idea in CI/CD pipeline especically for golang.

```bash
cfn --version
cfn 0.1.2
```

**Comment by rjlohan** [comment]
Is this specific to the Go plugin? The CLI calls a generate method in the plugin so I assume that's where this is occurring.

**Comment by sayboras** [comment]
> Is this specific to the Go plugin? The CLI calls a generate method in the plugin so I assume that's where this is occurring.

It could be related to Go plugin as I didn't try in other language yet. Let me open the similar issue in go repo.

**Comment by jotompki** [comment]
Closing this in favor of https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/issues/120
