### ISSUE TITLE
/target/aws-cloudformation-<project-name>-handler-1.0-SNAPSHOT.jar/ is an empty folder.

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-cli#407]
I'm following this guide here [1].

My build steps are as follows:

```
1.    cfn generate
2.   Build project in IntelliJ Idea
3.   sam local invoke TestEntrypoint --event sam-tests/create.json
```

I'm using Java8, Python3.7, let me know if I can provide any other versions.

[1] - https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html

**Comment by jotompki** [comment]
Try removing the folder and running `mvn package`. I am unsure of how your intellij workspace is configured so tough to tell if the build is intellij is doing what is intended.
