### ISSUE TITLE
Trying to Submit resource but getting error from CloudFormation registration

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-cli#408]
```
aws cloudformation describe-type-registration --registration-token 57157bbb-0d6d-4ac2-8616-8a7ec8ee3650
{
    "ProgressStatus": "FAILED", 
    "Description": "Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.UluruManagedProviderRuntimeException with error msg : [57157bbb-0d6d-4ac2-8616-8a7ec8ee3650] Error processing type artifact."
}
```

Any help would be greatly appreciated.

**Comment by richardhboyd** [comment]
For anyone else who comes across this issue, I experienced it too and it was the result of incorrectly packaging the deployment artifact. `cfn submit --dry-run` will emit a zip file that you can later share with others so they can run `aws cloudformation register-type ...`

**Comment by rclark** [comment]
What causes this problem? Is `cfn submit` basically just broken? When I used it...

1. It made 2 CloudFormation stacks in my account, one for S3 buckets, one for my resource provider's execution role.
2. It uploaded by `.zip` file to one of the S3 buckets.
3. I got the same error as the original post

👉 `cfn validate` passes.
👉 My attempt to register with `aws cloudformation register-type` encountered the same error.

```
$ aws cloudformation register-type \
  --type RESOURCE \
  --type-name "What::I::NamedIt" \
  --schema-handler-package s3://bucket-it-made/object-it-uploaded \
  --execution-role-arn arn-for-role-it-created
{
    "RegistrationToken": "36549044-fbfa-4569-87a7-7f796d32e9c4"
}

$ aws cloudformation describe-type-registration --registration-token 36549044-fbfa-4569-87a7-7f796d32e9c4
{
    "ProgressStatus": "FAILED",
    "Description": "Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [36549044-fbfa-4569-87a7-7f796d32e9c4] Error validating schema definition."
}
```

**Comment by ammokhov** [comment]
> What causes this problem? Is `cfn submit` basically just broken? When I used it...
> 
>     1. It made 2 CloudFormation stacks in my account, one for S3 buckets, one for my resource provider's execution role.
> 
>     2. It uploaded by `.zip` file to one of the S3 buckets.
> 
>     3. I got a similar error to the original post
> 
> 
> > Failed to register the type with registration token 'fd8608a0-d5ac-4071-aede-b5f3df95fb51'.
> > Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [fd8608a0-d5ac-4071-aede-b5f3df95fb51] Error validating schema definition.' ...
> 
> 👉 `cfn validate` passes.
> 👉 My attempt to register with `aws cloudformation register-type` encountered the same error.
> 
> ```
> $ aws cloudformation register-type \
>   --type RESOURCE \
>   --type-name "What::I::NamedIt" \
>   --schema-handler-package s3://bucket-it-made/object-it-uploaded \
>   --execution-role-arn arn-for-role-it-created
> {
>     "RegistrationToken": "36549044-fbfa-4569-87a7-7f796d32e9c4"
> }
> 
> $ aws cloudformation describe-type-registration --registration-token 36549044-fbfa-4569-87a7-7f796d32e9c4
> {
>     "ProgressStatus": "FAILED",
>     "Description": "Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [36549044-fbfa-4569-87a7-7f796d32e9c4] Error validating schema definition."
> }
> ```

do you have all contract tests passed? we are currently blocking registration if there are any failures

**Comment by rclark** [comment]
Thanks for taking a look. AWS support helped me find an issue -- it was syntax in the resource definition JSON that `cfn validate` did not catch -- I had a 

```
"writeOnlyProperties": [
  "PropertyName"
]
```

... which needed to be ...

```
"writeOnlyProperties": [
  "/properties/PropertyName"
]
```
