### ISSUE TITLE
Allow running only part of the contract tests

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cloudformation-cli#412]
When developing a resource, you can spend a lot of time waiting for all contract tests to finish so you can see its output. Being able to specify tests on the command line, could speed this up significantly.

**Comment by jotompki** [comment]
This exists currently as we pass in [any unmatched args to pytest](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/test.py#L136).

To select certain tests, simply provide the test names using -k as explained [here](http://doc.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name).

For example, to only run the test which attempts to create a duplicate, you'd pass in:
```
cfn test -k contract_create_duplicate
```

Also I believe if tests fail, there is some pytest option displayed in the failure output which allows you to only rerun the ones that failed, though am not sure what the arg is off the top of my head, though I know it is displayed on failure.

**Comment by jotompki** [comment]
We also will deselect tests based off the schema, so if you don't have a certain operation defined in your schema, we will skip tests that involve it.

**Comment by rjlohan** [comment]
Let's get this added to docs @jotompki ?

**Comment by ikben** [comment]
This doesn't work for me? (I tried with the latest release and directly from master):

```shell
$ pip3 install --upgrade git+https://github.com/aws-cloudformation/cloudformation-cli.git --upgrade
[...]
Building wheels for collected packages: cloudformation-cli
[...]
Successfully built cloudformation-cli
Installing collected packages: cloudformation-cli
  Found existing installation: cloudformation-cli 0.1.2
    Uninstalling cloudformation-cli-0.1.2:
      Successfully uninstalled cloudformation-cli-0.1.2
Successfully installed cloudformation-cli-0.1.2
$ cfn test -k contract_create_duplicate
usage: cfn [-h] [--version] {init,validate,submit,generate,test,invoke} ...
cfn: error: unrecognized arguments: -k
```

**Comment by ikben** [comment]
Found the right command!

```
cfn test -- -k contract_create_duplicate
```
