### ISSUE TITLE
Use SAM CLI build command to package lambda

### ISSUE THREAD

**Issue by eduardomourar** [aws-cloudformation/cloudformation-cli#416]
It would be nice to have the [SAM CLI build command](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) (which uses [this library](https://github.com/awslabs/aws-lambda-builders)) to package the lambda code for each language. If done in a generic way, the runtime plugins wouldn't need to implement own login for packaging.

**Comment by rjlohan** [comment]
This is actually by design. The fact that the backend runs your handlers on Lambda is an implementation detail that we might want to change over time. We don't want to tie more tightly to Lambda architecture by using SAM CLI for build.
