### ISSUE TITLE
AWS::Serverless::HttpApi: DefinitionUri is not transformed by the "package" command 

### ISSUE THREAD

**Issue by jvroig** [aws-cloudformation/cloudformation-cli#420]
For resources of **AWS::Serverless::HttpApi**, DefinitionUri is not being transformed by the "package" command from local path to S3 path. (Note, this is "HttpApi", which is relatively new). This results in the error _"'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter."_ in my CI/CD pipeline, since the local path was untouched.

Expected behavior: Similar to the old REST API resource [AWS::Serverless:Api] local path should be transformed to S3 path.

The relevant documentation for HttpApi confirms that this is the desired behavior. See the "DefinitionUri" section in its documentation page: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-definitionuri

Thanks, CloudFormation team!

**Comment by jotompki** [comment]
Hi is this related to the sam-cli or the cloudformation-cli? the latter is used for creating resource types. I'd cut an issue  against the [sam-cli](https://github.com/awslabs/aws-sam-cli) repo as this seems unrelated to the cloudformation-cli.

**Comment by jvroig** [comment]
Thanks for the feedback. I'd be happy to post this issue in that Repo if that's more appropriate, but to clarify,I discovered this issue using just cloudformation CLI, not the SAM CLI.

In my Build stage (c/o CodeBuild), the command I execute is **aws cloudformation package**. The relevant documentation page for **cloudformation package** is this: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

You'll note in that documentation page that it specifically lists AWS::Serverless::API as a resource it transforms, but does not mention the newer (just March GA) AWS::Serverless::HttpApi which is supposed to work the same way. From what I understand, **sam package** simply calls **aws cloudformation package**, so I thought this was the more appropriate repo to file a bug report to than the SAM group.

Given this, are you still of the opinion this should be transferred to sam-cli? I'll happily transfer this to whoever is ultimately the correct person to file this bug report to.

Thanks!

**Comment by jotompki** [comment]
> Thanks for the feedback. I'd be happy to post this issue in that Repo if that's more appropriate, but to clarify,I discovered this issue using just cloudformation CLI, not the SAM CLI.
> 
> In my Build stage (c/o CodeBuild), the command I execute is **aws cloudformation package**. The relevant documentation page for **cloudformation package** is this: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html
> 
> You'll note in that documentation page that it specifically lists AWS::Serverless::API as a resource it transforms, but does not mention the newer (just March GA) AWS::Serverless::HttpApi which is supposed to work the same way. From what I understand, **sam package** simply calls **aws cloudformation package**, so I thought this was the more appropriate repo to file a bug report to than the SAM group.
> 
> Given this, are you still of the opinion this should be transferred to sam-cli? I'll happily transfer this to whoever is ultimately the correct person to file this bug report to.
> 
> Thanks!

My apologies I didn't understand the issue fully. I would cut an issue against the [aws-cli repo](https://github.com/aws/aws-cli/labels/cloudformation%20package%2Fdeploy) as that repository contains [the logic related to packaging.](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/package.py)
