### ISSUE TITLE
"cfn test" gives "UnboundLocalError: local variable 'updated_model' referenced before assignment"

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cloudformation-cli#426]
https://github.com/aws-cloudformation/cloudformation-cli/blob/dbf6dc34f1ee52b9baf6d0a78b1e62e7f06f83d7/src/rpdk/core/contract/suite/handler_update.py#L26-L30

I think that snippet is the reason why while running the contract tests I get 

```
ERROR handler_update.py::contract_update_read_success - UnboundLocalError: local variable 'updated_model' referenced before assignment
ERROR handler_update.py::contract_update_list_success - UnboundLocalError: local variable 'updated_model' referenced before assignment
```

**Comment by jotompki** [comment]
Is your update handler returning successfully? I have a hunch that this call is failing so the updated model isn't getting set:
https://github.com/aws-cloudformation/cloudformation-cli/blob/dbf6dc34f1ee52b9baf6d0a78b1e62e7f06f83d7/src/rpdk/core/contract/suite/handler_update.py#L23-L25

then we try using the model during cleanup:
https://github.com/aws-cloudformation/cloudformation-cli/blob/dbf6dc34f1ee52b9baf6d0a78b1e62e7f06f83d7/src/rpdk/core/contract/suite/handler_update.py#L28-L31

Ideally we should just have some cleanup model that we first set to the update request, then the model after creation

**Comment by miparnisari** [comment]
> Is your update handler returning successfully?

No :D but still, I think the `finally` block should be changed to consider this possibility

**Comment by jotompki** [comment]
Yeah that's just a bug, we handle it correctly for the create fixture by setting a model to the requested model then the returned model to handle :

https://github.com/aws-cloudformation/cloudformation-cli/blob/dbf6dc34f1ee52b9baf6d0a78b1e62e7f06f83d7/src/rpdk/core/contract/suite/handler_create.py#L23-L31

I'll send out a quick fix
