### ISSUE TITLE
Caller ID, but for Resources 

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli#434]
I’d like the ability to know who (IAM Principal) called the ExecuteChangeSet operation. There are cases (Cloud9 EnvironmentEC2) where the provider needs to explicitly state that the resource is being created on behalf of another principal.

I would even settle for being able to say “execute my provider with the intersection of permissions between my resource-role and the caller” for some use-cases.

**Comment by ikben** [comment]
The intersection permissions is similar to what I suggested here: https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/issues/91#issuecomment-606740362

IAM is one area where I can't call Resource Providers "a lot like native CloudFormation", and I would really like to be able to do that.
