### ISSUE TITLE
Artifact upload best practices

### ISSUE THREAD

**Issue by wulfmann** [aws-cloudformation/cloudformation-cli#439]
What are the best practices / recommended way of handling artifacts that may be needed for a resource provider?

Example:

I create a resource provider for a service that “deploys” a jar file. It requires a zip to be uploaded to their proprietary artifact store.

This would technically be a versioned asset which might be something I’d like in cloudformation. Would this be a bad path to take?

Would it be better to simply have a deployment resource and handle the artifact upload beforehand?

How does lambda solve this?

**Comment by ikben** [comment]
@wulfmann Lambda solves this with having the artifact on S3 and creating resources based on that (mostly, they also support inline code, which I believe is less relevant for your question).

Assuming what you want to achieve is:
- I have a jar file locally
- I want this into a third party artifact store
- And use that artifact in my resoource.

I would:
1. create a Org::ArtifactStore::JarArtifact resource provider that takes an S3 url and uploads that to the store
2. use that JarArtifact as an input when I write the real resource provider
3. upload the jar to S3 
4. Create a template (or mulitple) that contains both the JarArtifact and RealResource

If the artifact store and the resource itself are tightly coupled (like with lambda), you could make that artifact resource a nested porperty of your real resource.

Relevant links for lambda:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-layerversion-content.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html

You will have to think about which inputs/outputs you'll use to trigger replacements when updating to a new jar file

**Comment by wulfmann** [comment]
@ikben that pattern makes sense to me. One piece that I think I’m still missing is the actual upload to the 3rd party artifact store.

Some of the runtime environment of a resource provider is still a bit dark to me, but are you suggesting hat during the real resource creation, the s3 artifact (that’s passed in) is downloaded and then uploaded to the 3rd party?

Is there a memory limit for the resource provider? I’m assuming there is some sort of file system constraint as well?
