### ISSUE TITLE
Register Type parameters are not very clear

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli#440]
The [ExecutionRoleArn](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.register_type) parameter says that this is the role used to register the type and also says that I, as the person consuming the type by registering it, must create an Execution Role to be used by the type, but doesn't show or link to a way to connect that created Role to this type. 

Usually an AWS CLI operation will use the `--profile` or `--role-arn` parameter for specifying the role to use to perform this action. Is the first sentence in the description inaccurate?

```text
ExecutionRoleArn (string) -- The Amazon Resource Name (ARN) of the IAM execution role to use to register the type. If your resource type calls AWS APIs in any of its handlers, you must create an * IAM execution role * that includes the necessary permissions to call those AWS APIs, and provision that execution role in your account. CloudFormation then assumes that execution role to provide your resource type with the appropriate credentials.
```

**Comment by rjlohan** [comment]
Agree it's not clear. The role is only used when executing the provider. It is assumed by CloudFormation to create a temporary session token which is passed to the provider. The IAM Identity used to Register the type is the one which calls the `RegisterType` API.

**Comment by rjlohan** [comment]
Is this better now?

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RegisterType.html
