### ISSUE TITLE
[contract tests] create tests do not pass updated resource model

### ISSUE THREAD

**Issue by ammokhov** [aws-cloudformation/cloudformation-cli#445]
```
handler_create.py::contract_create_delete
handler_create.py::contract_create_duplicate
handler_create.py::contract_create_read_success
handler_create.py::contract_create_list_success
```
following tests do not pass updated resource model on handler reinvocation, which causes issues for the resources that have primary identifier as `readOnly` property

**Comment by anshikg** [comment]
can you please provide with the stack trace or the error message for each of the resources. Also, could you mention the resource you are working on.

**Comment by ammokhov** [comment]
this is relevant to any resource where primary id is read only and create handler requires stabilization. Once resource is created the updated resource model is returned by the handler but not received one reinvocation, hence the test just runs forever (cant get passed first step since it receives model without primary id) and creates a bunch of duplicate resources.

**Comment by ammokhov** [comment]
sample trace of four consecutive invocations of the handler by the test `handler_create.py::contract_create_delete`

```
[CREATE] invoking handler…
ResourceModel(primaryId=null)
[CREATE] handler invokedEND

[CREATE] invoking handler…
ResourceModel(primaryId=null)
[CREATE] handler invokedEND

[CREATE] invoking handler…
ResourceModel(primaryId=null)
[CREATE] handler invokedEND

[CREATE] invoking handler…
ResourceModel(primaryId=null)
[CREATE] handler invokedEND
```

**Comment by anshikg** [comment]
Hey @ammokhov could you please provide a stack trace when you run the contract test. If you are trying to create a resource whose primary Identifier is readOnly I would expect the input to the identifier to be null. It would be helpful to get the input and output to the contract test to see what is exactly happening. You could run a specific contract test using the following command:
```
cfn test -- -k contract_create_delete
```
The above should give you a detailed stack on your terminal.
