### ISSUE TITLE
Contract test Bugs

### ISSUE THREAD

**Issue by anshikg** [aws-cloudformation/cloudformation-cli#455]
I ran into a few Contract test issue while running them on my resource:

- [x] While comparing the created model with the model in the request, I get assert failure. It looks like the model is the same but the downstream service returns empty objects/lists in the resulting model which causes assertion issue.
test cases where I see this issue: 

- handler_create.py::contract_create_read_success

- handler_create.py::contract_create_list_success

- handler_update.py::contract_update_read_success

- [x] In resources which are implemented call chaning it is difficult to remove the model after the delete call is successful. I don't see a point in asserting if resource model is returned in an unsuccessful call
test cases where I see this issue: 

- handler_create.py::contract_create_duplicate

- handler_delete.py::contract_delete_update

- [x] In case of call channing, if a call is unsuccessful there should be a way to pass the right erroCode and message for a meaningful failure.

- contract_invalid_create

- contract_update_create_only_property 

- contract_update_non_existent_resource

**Comment by ddarbari** [comment]
+1

**Comment by praghu1** [comment]
+1

**Comment by advaj** [comment]
+1

**Comment by ammokhov** [comment]
point 2:
```java
        return proxy.initiate("AWS-Logs-MetricFilter::Delete", proxyClient, model, callbackContext)
                .translateToServiceRequest(Translator::translateToDeleteRequest)
                .makeServiceCall(this::deleteResource)
                .done(awsResponse -> ProgressEvent.<ResourceModel, CallbackContext>builder()
                    .status(OperationStatus.SUCCESS)
                    .build());
```

point 3:
```java
        return proxy.initiate("rds::delete-dbsubnet-group", proxyClient, request.getDesiredResourceState(), callbackContext)
            .translateToServiceRequest(Translator::deleteDbSubnetGroupRequest)
            .backoffDelay(CONSTANT)
            .makeServiceCall((deleteDbSubnetGroupRequest, proxyInvocation) -> proxyInvocation.injectCredentialsAndInvokeV2(deleteDbSubnetGroupRequest, proxyInvocation.client()::deleteDBSubnetGroup))
            .stabilize((deleteDbSubnetGroupRequest, deleteDbSubnetGroupResponse, proxyInvocation, resourceModel, context) -> isDeleted(resourceModel, proxyInvocation))
            .handleError((deleteDbSubnetGroupRequest, exception, client, resourceModel, cxt) -> {
                if (exception instanceof DbSubnetGroupNotFoundException)
                    return ProgressEvent.defaultFailureHandler(exception, HandlerErrorCode.NotFound);
                throw exception;
            })
```

**Comment by anshikg** [comment]
#2 We need to ensure the Delete handler does not return resource model. As @ammokhov mentioned above for point 2 we can return a progress event with the updated model. This will avoid the model assert for delete handler.

**Comment by anshikg** [comment]
#3 Returning both Exception and Progress Event work. I am not if some code change was pushed to fix this functionality

**Comment by anshikg** [comment]
#1 was happening in case your read only properties are not set to the resource model returned from create handler. In my case, I returned readHandler progress event once, the resource was created.
