### ISSUE TITLE
Downstream service does not support functionality Contract test is testing

### ISSUE THREAD

**Issue by anshikg** [aws-cloudformation/cloudformation-cli#456]
Contract test tries to delete a resource and then deletes it one more time to check if the downstream service throws NotFound exception. CloudWatch Alarm resource does not throw an exception if we try to a delete a resource which does not exist. Should CFN be throwing an error?
Right now the contract test: contract_delete_delete fails for me. 

What is the expectation from CFN resource?

**Comment by rjlohan** [comment]
Per the [contract](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html);

> A delete hander MUST return FAILED with a NotFound error code if the if the resource did not exist prior to the delete request.

CloudFormation itself chooses to ignore this error during stack workflows, but the resource must respond this way as the customer-specified intent to delete cannot be fulfilled.

**Comment by anshikg** [comment]
Resolved this issue in the handler.
