### ISSUE TITLE
Modelling Create actions for APIs with PUT semantics

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/cloudformation-cli#458]
Provide guidance on how resource types should be modelled around APIs which have a HTTP PUT semantic, or "upsert" behaviour. 

Specifically, give examples and guidance on how to achieve the following aspect of the `Create` [handler contract](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html);

> A create handler MUST return FAILED with an AlreadyExists error code if the resource already existed prior to the create request.

**Comment by x6j8x** [comment]
I currently solve this by a "read" before "create", but yeah, its kind of clunky.

**Comment by ikben** [comment]
Examples of resources that I think are currently have to deal with upserting in some way:

- [AWS::Lambda::Permission](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
)
- [AWS::IAM::Policy][https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html]
- [AWS::EC2::SecurityGroupIngress](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html)
- [AWS::Route53::RecordSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html)

**Comment by rjlohan** [comment]
There's alot of examples actually, but they are in the overall minority. Read before Create is how we recommend teams achieve this is their underlying service isn't already checking for pre-existence. There's an example of this in the [`AWS::Logs::MetricFilter1](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/master/aws-logs-metricfilter/src/main/java/software/amazon/logs/metricfilter/CreateHandler.java#L55) resource.

**Comment by PatMyron** [comment]
At least for Java, @ammokhov has added this to the generated `CreateHandler`:
https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/240/files#diff-29964294df5be341d1049cfd65048a6f334e57c2357fea4f107043ca97d67dc9R88
https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/266
