### ISSUE TITLE
Assertions checks `current_resource_model` and not the actual response

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/cloudformation-cli#462]
There were several new assertions added that perform their checks on the `current_resource_model` instead of on the actual response model. 

Currently, that leads to failing tests for our resources as we do return "fresh" models from the callbacks (and to my knowledge nothing in the contract demands otherwise). 

Examples:

https://github.com/aws-cloudformation/cloudformation-cli/blob/a25024517be2d1037300497d762eea2f1d890fd5/src/rpdk/core/contract/suite/handler_commons.py#L13

https://github.com/aws-cloudformation/cloudformation-cli/blob/a25024517be2d1037300497d762eea2f1d890fd5/src/rpdk/core/contract/suite/handler_commons.py#L15

**Comment by x6j8x** [comment]
Just validated against HEAD (Commit: 85dba80439e044f65e294af65d36fa0934151bad) - works again. 

Thanks! :)

**Comment by massi-ang** [comment]
This commit should be published in `pip` as the latest version there (v0.1.4) still exhibit the error
