### ISSUE TITLE
Write Only property fails to assert on nested properties

### ISSUE THREAD

**Issue by anshikg** [aws-cloudformation/cloudformation-cli#478]
In case of nested write only properties: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-elasticloadbalancingv2/blob/master/aws-elasticloadbalancingv2-listener.json#L325

The contract test fails to assert: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/suite/handler_commons.py#L15

The test fails with the following stack trace:  
```
resource_model = {'AlpnPolicy': [], 'Certificates': [], 'DefaultActions': [{'ForwardConfig': {'TargetGroups': [{'TargetGroupArn': 'arn:...'arn:aws:elasticloadbalancing:us-east-1:362761549384:listener/net/MCM-29093805/37e4ea061f7d3f55/ee53b3bd90797dba', ...}
write_only_property = ('properties', 'DefaultActions', 'AuthenticateOidcConfig', 'ClientSecret')

    @staticmethod
    def key_error_safe_traverse(resource_model, write_only_property):
        try:
            return traverse(
>               resource_model, fragment_list(write_only_property, "properties")
            )[0]

../cloudformation-cli/cloudformation-cli/src/rpdk/core/contract/resource_client.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

document = [{'ForwardConfig': {'TargetGroups': [{'TargetGroupArn': 'arn:aws:elasticloadbalancing:us-east-1:362761549384:targetgro...tGroupArn': 'arn:aws:elasticloadbalancing:us-east-1:362761549384:targetgroup/CFN/c78de428819d902c', 'Type': 'forward'}]
path_parts = ['DefaultActions', 'AuthenticateOidcConfig', 'ClientSecret']

    def traverse(document, path_parts):
        """Traverse the document according to the reference.
    
        Since the document is presumed to be the reference's base, the base is
        discarded. There is no validation that the reference is valid.
    
        :raises ValueError, LookupError: the reference is invalid for this document
    
        >>> traverse({"foo": {"bar": [42]}}, tuple())
        ({'foo': {'bar': [42]}}, (), None)
        >>> traverse({"foo": {"bar": [42]}}, ["foo"])
        ({'bar': [42]}, ('foo',), {'foo': {'bar': [42]}})
        >>> traverse({"foo": {"bar": [42]}}, ("foo", "bar"))
        ([42], ('foo', 'bar'), {'bar': [42]})
        >>> traverse({"foo": {"bar": [42]}}, ("foo", "bar", "0"))
        (42, ('foo', 'bar', 0), [42])
        >>> traverse({}, ["foo"])
        Traceback (most recent call last):
        ...
        KeyError: 'foo'
        >>> traverse([], ["foo"])
        Traceback (most recent call last):
        ...
        ValueError: invalid literal for int() with base 10: 'foo'
        >>> traverse([], [0])
        Traceback (most recent call last):
        ...
        IndexError: list index out of range
        """
        parent = None
        path = []
        for part in path_parts:
            if isinstance(document, Sequence):
>               part = int(part)
E               ValueError: invalid literal for int() with base 10: 'AuthenticateOidcConfig'

../cloudformation-cli/cloudformation-cli/src/rpdk/core/jsonutils/utils.py:99: ValueError
```

**Comment by jotompki** [comment]
DefaultActions is an array, no? You'd have to make the path something like  `"/properties/DefaultActions/0/AuthenticateOidcConfig/ClientSecret"` for it to work

**Comment by araphn** [comment]
Hello, I'm also seeing this error for readOnlyProperties when running contract test for contract_create_read_success for our resource when i did "/properties/Subscribers/*/Status". When I switched to "/properties/Subscribers/0/Status", the error went away. What about array that has more than 1 object?

**Comment by PatMyron** [comment]
From searching [all other resource provider schemas in `us-east-1`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html):

```bash
~/Downloads/CloudformationSchemas $ grep -E 'OnlyProperties".*"/properties/\w*/' *
...
aws-elasticloadbalancingv2-listener.json:  "writeOnlyProperties" : [ "/properties/DefaultActions/*/AuthenticateOidcConfig/ClientSecret", "/properties/DefaultActions/*/ForwardConfig", "/properties/DefaultActions/*/TargetGroupArn" ],
```
[`AWS::ElasticLoadBalancingV2::Listener` is already using `*`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-elasticloadbalancingv2/blob/2a0922151af454755fe3e578fd3c767391c2aad3/aws-elbv2-listener/aws-elasticloadbalancingv2-listener.json#L277+L281) and no resource schemas seem to be using numbers like that yet

**Comment by araphn** [comment]
Hi all, is there any update on this certain issue? This is still a problem for our team.

**Comment by privetjr** [comment]
I'm still seeing this limitation with readOnly properties with cloudformation-cli v0.2.6 (and resource providers created with `cloudformation-cli-python-lib==2.1.5`). The resource handlers work as expected, but contract tests fail due to the output model having additional readonly properties for list members.

**Comment by colltoth** [comment]
I'm seeing this as well on the latest version of the CLI and java plugin
