### ISSUE TITLE
Contract tests issue with a dependent resource

### ISSUE THREAD

**Issue by boweix-amz** [aws-cloudformation/cloudformation-cli#483]
So when we flow a resource through pipeline to make it public, contract tests will block if it failed. Currently what we see is contract test either generate the resource model template according to schema or we can provide input files for our own test case.

But in our case, we need to provide a resource arn which is pre-created not through cloudformation(also some other arns like organization account ARN.) Wonder how can we provide these info when resource run contract tests to flip to public.

**Comment by boweix-amz** [comment]
contract

**Comment by anshikg** [comment]
As discussed offline, This feature is already implemented and is being used. Feel free to open this issue if this is still a concern.
