### ISSUE TITLE
Contract test failed due to bad escape

### ISSUE THREAD

**Issue by boweix-amz** [aws-cloudformation/cloudformation-cli#484]
When run contract test locally, we are getting bad escape \p at position 1.
The schema is validate though cli and worked fine with end-to-end manual test with register type.

And another resource works fine when run in same environment so there shouldn't be any cli or python version issue.

>                   raise source.error('bad escape %s' % escape, len(escape))
E                   re.error: bad escape \p at position 1

/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py:337: error

**Comment by boweix-amz** [comment]
Find the issue with [\\p{L}\\p{M}\\p{Z}\\p{S}\\p{N}\\p{P}]* double\\. But replace double slash with single one will cause cfn validate failure

**Comment by anshikg** [comment]
This seems like a non-issue now. Closing this. Feel free to open this if there are any concerns.
