### ISSUE TITLE
contract_update_create_only_property's call to Create Handler has AlreadyExists Error

### ISSUE THREAD

**Issue by cortez7** [aws-cloudformation/cloudformation-cli#488]
When I run contract tests, on the 2nd to last one, handler_update.py::contract_update_create_only_property, I get an AlreadyExists failure on the initial creation at the start of the test. Sometimes I get a timeout error in one of the Read or List Handlers, but even when I don't get a timeout error, I still get an AlreadyExists error on contract_update_create_only_property.

[Contract Test Results](https://paste.amazon.com/show/cortpage/1594667429)

When I run this test by itself, it passes.

I enter a sample LoadBalancerName (which is the primary id) in the overrides.json. I tried removing this override, but the contract tests just generate a name of “0” and the same thing happens. I tried entering null to force a random name generation, but when null is passed to the Delete handler, it doesn’t know what resource to delete.

The contract tests didn’t delete the resource beforehand so the AlreadyExists failure is expected. Looking at rpdk.log, the order of calls leading up to the error is Delete, Create, Update, Read, List, Create with AlreadyExists error.

**Comment by ammokhov** [comment]
regarding RL timout - should this solve it (#486)?

**Comment by cortez7** [comment]
Yes, I think that will.

**Comment by anshikg** [comment]
Waiting on @cortez7 for stack trace for the failing contract test

**Comment by cortez7** [comment]
I re-ran tests with a local copy of https://github.com/aws-cloudformation/cloudformation-cli. I happened to not get errors due to timeouts this time, but the last 2 tests still fail.
[Contract Test Results](https://paste.amazon.com/show/cortpage/1594772142)
