### ISSUE TITLE
Logs for contract test run while submitting resource not found

### ISSUE THREAD

**Issue by rajdivya** [aws-cloudformation/cloudformation-cli#508]
When running `cfn submit` for a resource I got this message 

> 'Description': 'Deployment is currently in DEPLOY_STAGE of status COMPLETED; [Warning] Contract test status is FAILED. View s3 logs for details.'

However, I couldn't find any the logs or the correct bucket in S3. It will be useful if the bucket name was also included in the message.

**Comment by anshikg** [comment]
talked to Divya offline and provided the right documentation
