### ISSUE TITLE
Contract test for creating a non existent resource failing

### ISSUE THREAD

**Issue by rajdivya** [aws-cloudformation/cloudformation-cli#512]
Tests for creating a non existent resource fails with an invalidRequest exception when the resource's read only property is also its primary identifier. 

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-gamelift/blob/master/aws-gamelift-alias/aws-gamelift-alias.json#L72-L77

Failure message:
```
status = <OperationStatus.FAILED: 'FAILED'>
response = {'callbackDelaySeconds': 0, 'errorCode': 'InvalidRequest', 'message': 'Alias Id is required (Service: GameLift, Status Code: 400, Request ID: ab8dd74b-a1b9-4138-9309-838acf970072)', 'status': 'FAILED'}

    @staticmethod
    def assert_success(status, response):
>       assert status == OperationStatus.SUCCESS, "status should be SUCCESS"
E       AssertionError: status should be SUCCESS

/usr/local/lib/python3.7/site-packages/rpdk/core/contract/resource_client.py:256: AssertionError

```

**Comment by LaikaN57** [comment]
@rajdivya This looks like more of a usage issue, not an issue with tests. It looks like GameLift is returning an error as you are not passing an Alias Id. Can you please provide a bit more information on what API you are trying to call and share some of the relevant json schema?

**Comment by anshikg** [comment]
@rajdivya I am cloasing this issue as I concour with @LaikaN57 Feel free to re-open if this is still a concern.
