### ISSUE TITLE
Contract testing of create handler properties: case where return model cannot always be equal to specified model

### ISSUE THREAD

**Issue by anticobalt** [aws-cloudformation/cloudformation-cli#516]
From what I know, the contract tests don't currently test the [contract requirement](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html#resource-type-test-contract-create) that properties in the create handler's return model must be exactly the same specified model.

However, if/when this test gets added, is it possible to account for situations where the return model cannot always be exactly the same as the specified model (excluding write-only properties)? For example, if a property is set to a default value due to no value being specified, or if a property being null or empty (e.g. empty list) is considered equivalent in the downstream service.

Example:
1. Input model has a property `optional_key`=null
2. Create handler passes model to underlying service, and service generates a key for this resource since none is specified.
3. Create handler invokes read handler to get resource, and constructs model with `optional_key`=MY_GENERATED_KEY
4. Create handler returns model with a key that is different than specified key, which violates contract

**Comment by anshikg** [comment]
@anticobalt could add a link to your schema?

1. Input model has a property optional_key=null
> What is the issue here?

2. Create handler passes model to underlying service, and service generates a key for this resource since none is specified.
> Is this property read only? If not, you should consider setting it  accordingly

3. Create handler invokes read handler to get resource, and constructs model with optional_key=MY_GENERATED_KEY
> Could you explain this situation a little more

4. Create handler returns model with a key that is different than specified key, which violates contract
> so, the input property is "xyz" and after create it is set to "abc"?

**Comment by anticobalt** [comment]
> What is the issue here?

There's no issue with this. In this example, the property is optional, so can be null or an actual string value

> Is this property read only? If not, you should consider setting it accordingly

It's create-only.

> Could you explain this situation a little more

Based on the code generated by the guided-aws option during `cfn init`, I'm guessing that create handlers should invoke the read handler after resource creation, and return the read handler's result to get all resource properties. So, when that happens, because the resource was created without a supplied `optional_key`, the downstream service will assign a value to that property, and that value will be set to the model returned by the read handler.

> so, the input property is "xyz" and after create it is set to "abc"?

input property is null (i.e. not specified) and after create it is set to "abc"

**Comment by Yanling-Wu** [comment]
Hello, 
Any updates for this issue? 

My team also met this issue. For example, if the customers didnt specify the value of `PlatformArn`, our service will generate it based on the `SolutionStackName` that the customers passed. But it will fail to validate the input and output. Because the input didnt include `PlatformArn` but the output included it.

**Comment by prerna-p** [comment]
> Hello,
> Any updates for this issue?
> 
> My team also met this issue. For example, if the customers didnt specify the value of `PlatformArn`, our service will generate it based on the `SolutionStackName` that the customers passed. But it will fail to validate the input and output. Because the input didnt include `PlatformArn` but the output included it.

hi @Yanling-Wu , recently we made a change to our logic for testing the input model against the output model. This should address the issue you're facing wherein the resource is falsely detected as drifted by the contract test. We're tracking the issue here #580
