### ISSUE TITLE
AWS Amplify Set-Up with Cloud Formation different from console and causing issues

### ISSUE THREAD

**Issue by eric-feng-2011** [aws-cloudformation/cloudformation-cli#528]
Issue:
Cloud Formation set up of Amplify instance is different from Amplify console and is causing errors.

Steps to reproduce:
1. Create an AWS Amplify instance through a Cloud Formation template. I'm currently using the one below:
```
    "AmplifyInstance": {
      "Type" : "AWS::Amplify::App",
      "Properties" : {
        "Description" : "Auto create amplify resource for wild rides site",
        "IAMServiceRole" : {
          "Fn::GetAtt" : ["AmplifyRole", "Arn"]
        },
        "Name" : "test-name",
        "AccessToken": {
          "Ref": "AmplifyAuthToken"
        },
        "Repository" : {
          "Ref": "AmplifyCodeRepository"
        },
        "EnvironmentVariables": [
          {
            "Name" : "REACT_APP_API_URL",
            "Value" : {
              "Fn::Sub": "https://${GatewayRest}.execute-api.${Region}.amazonaws.com/${StageName}"
            }
          },
          {
            "Name": "REACT_APP_ENDPOINT_NAME",
            "Value": {
              "Ref": "EndpointName"
            }
          },
          {
            "Name": "REACT_APP_EXTRA_INFO",
            "Value": {
              "Ref": "ExtraInfo"
            }
          }
        ]
      }
    },
    "AmplifyBranch": {
      "Type": "AWS::Amplify::Branch",
      "Properties": {
        "BranchName": "master",
        "AppId": {"Fn::GetAtt" :  ["AmplifyInstance", "AppId"]},
        "EnableAutoBuild": false
      }
    },
    "AmplifyDomain": {
      "Type": "AWS::Amplify::Domain",
      "DependsOn": "AmplifyBranch",
      "Properties": {
        "AppId": {"Fn::GetAtt" :  ["AmplifyInstance", "AppId"]},
        "DomainName": {
          "Fn::Join" : [
            "", [
              {
                "Fn::GetAtt" : ["AmplifyInstance", "AppId"]
              },
              ".amplifyapp.com"
            ]
          ]
        },
        "SubDomainSettings": [{
          "BranchName": "master",
          "Prefix": "master"
        }]
      }
    }
```
The various variables are passed in as string parameters, and ExtraInfo in particular is a large JSON string. The code repository is a github repository.

2. Try calling the connecting API Gateway url with ExtraInfo and Endpoint Name as extra headers. Something like the following:
```
fetch(url,
            {
                method: 'POST',
                headers: {
                    'endpoint-name': process.env.REACT_APP_ENDPOINT_NAME,
                    'extra-info': process.env.REACT_APP_EXTRA_INFO
                },
                body: body
            });
```

3. The resulting call fails. I've confirmed that without the large extra-info header that the API call works. I've also made sure that the API-Gateway allows the extra-info header tag. 

Expected behavior:
I expect the resulting call to work. I use the exact same code, but put it in a code commit repository and manually deploy it via the AWS Amplify console. This amplify instance is directed to point to the same API Gateway as the one launched by the cloud formation template. When I call my REST API with this app, the call succeeds.

There is some configuration that I am losing between the cloudformation template and the amplify console. What am I missing, and how can I add it?

**Comment by PatMyron** [comment]
Unfortunately, this repository is specifically for issues with the [CloudFormation Registry CLI](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/), but I recommend checking out [Former2](https://github.com/iann0036/former2#security) if you're experiencing troubles exactly replicating specific environments created outside of CloudFormation

**Comment by rjlohan** [comment]
You may also want to raise a support case for this issue at https://console.aws.amazon.com/support/home

**Comment by eric-feng-2011** [comment]
Just for anyone that is having the same issue, my problem was two-fold.

The first issue was that I was unnecessarily creating another domain for my master branch with the exact same name as the another one. I think because there were two same domains, the amplify app got confused (or something similar).

The second issue was that there was an issue with how I was parsing the JSON in the backend and sending it to the REST API. This gave me a 403 error and resolving the JSON parse issue made this go away.
