### ISSUE TITLE
Inconsistency in CFN JSON schema definition regarding max timeout value

### ISSUE THREAD

**Issue by wundr20** [aws-cloudformation/cloudformation-cli#538]
Even though the [documentation](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html) about CFN-CLI 2.0 states that up to 48 hours of polling is supported as shown in this photo,
![image](https://user-images.githubusercontent.com/67343044/89962763-55c5d180-dc0b-11ea-92ac-28b1b8320b07.png)
the handler definition in the provider definition schema.v1.json limits the max timeout value to only 720 minutes = 12 hours instead of 2880 minutes = 48 hours. 

Can someone elaborate if 48 hours of stabilization/polling is actually supported by CFN? If not, what are some ways we can override or specify the polling behavior when using call chaining? In the previous cfn init 1.0 version, this same logic was controlled by constructing the CallbackContext with a specific MAX_NUMBER_STABILIZATION_RETRIES and returning a ProgressEvent with specific POLL_DELAY_IN_MS constants. Is this functionality/flexibiity removed when developing with cfn init 2.0 (guided aws) version?

**Comment by ammokhov** [comment]
> Even though the [documentation](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html) about CFN-CLI 2.0 states that up to 48 hours of polling is supported as shown in this photo,
> ![image](https://user-images.githubusercontent.com/67343044/89962763-55c5d180-dc0b-11ea-92ac-28b1b8320b07.png)
> the handler definition in the provider definition schema.v1.json limits the max timeout value to only 720 minutes = 12 hours instead of 2880 minutes = 48 hours.
> 
> Can someone elaborate if 48 hours of stabilization/polling is actually supported by CFN? If not, what are some ways we can override or specify the polling behavior when using call chaining? In the previous cfn init 1.0 version, this same logic was controlled by constructing the CallbackContext with a specific MAX_NUMBER_STABILIZATION_RETRIES and returning a ProgressEvent with specific POLL_DELAY_IN_MS constants. Is this functionality/flexibiity removed when developing with cfn init 2.0 (guided aws) version?

you could use back off delay strategy - [example](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/blob/81c18fbc1583563c5f870a6a49df28553870e51e/aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java#L138)
