### ISSUE TITLE
.NET Core Language Plugin

### ISSUE THREAD

**Issue by jonathanmorley** [aws-cloudformation/cloudformation-cli#545]
Is there a plan to have .NET Core language plugin supported?

**Comment by ammokhov** [comment]
> Is there a plan to have .NET Core language plugin supported?

.NET integration is WIP

**Comment by cmgorton** [comment]
Hey @jonathanmorley. We are working on answering and cleaning up stale issues. 

It looks like this question was answered but feel free to reopen this issue so we can investigate it further. 

You can also ask questions in our [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) channel for a more prompt response.
