### ISSUE TITLE
Unhandled exception (rpdk.log included)

### ISSUE THREAD

**Issue by suhaniladani** [aws-cloudformation/cloudformation-cli#563]
- Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/generate.py", line 16, in generate
    project.generate_docs()
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 384, in generate_docs
    docs_schema["properties"] = {
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 385, in <dictcomp>
    name: self._set_docs_properties(name, value, (name,))
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 534, in _set_docs_properties
    __set_property_type(prop_item, single_type=single_item)
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 472, in __set_property_type
    propname, prop["items"], proppath
KeyError: 'items'

**Comment by ammokhov** [comment]
would you mind including your resource schema as well?

**Comment by suhaniladani** [comment]
{
    "typeName": "AWS::EC2::TransitGatewayMulticastDomainAssociation",
    "description": "Describes the resources associated with the transit gateway multicast domain.",
    "sourceUrl": "https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-transitgateway.git",
    "definitions": {
        "SubnetAssociation": {
            "type": "object",
            "properties": {
                "state": {
                    "description": "The state of the subnet association",
                    "type": "string",
                    "enum": [
                        "associating",
                        "associated",
                        "disassociating",
                        "disassociated"
                    ]
                },
                "subnetId": {
                    "description": "The ID of the subnet",
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    },
    "properties": {
        "resourceId": {
            "description": "The ID of the resource",
            "type": "string"
        },
        "resourceType": {
            "description": "The type of resource, for example a VPC attachment.",
            "type": "string",
            "enum": [
                "vpc",
                "vpn",
                "direct-connect-gateway",
                "tgw-peering"
            ]
        },
        "subnet": {
            "description": "The subnet associated with the transit gateway multicast domain",
            "$ref": "#/definitions/SubnetAssociation"
        },
        "transitGatewayAttachmentId": {
            "description":"The ID of the transit gateway attachment.",
            "type": "string"
        },
        "transitGatewayMulticastDomainId": {
            "description": "The ID of the transit gateway multicast domain.",
            "type": "string"
        },
        "SubnetIds": {
            "description": "The IDs of the subnets to associate with the transit gateway multicast domain.",
            "type":"array",
            "contains": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "transitGatewayAttachmentId",
        "transitGatewayMulticastDomainId",
        "SubnetIds"
    ],

    "createOnlyProperties": [
        "/properties/transitGatewayAttachmentId",
        "/properties/transitGatewayMulticastDomainId",
        "/properties/SubnetIds"
    ],
    "primaryIdentifier": [
        "/properties/transitGatewayMulticastDomainId",
        "/properties/transitGatewayAttachmentId",
        "/properties/subnet"
    ],
    "handlers": {
        "create": {
            "permissions": [
                "ec2:AssociateTransitGatewayMulticastDomain"
            ]
        },
        "read": {
            "permissions": [
                "ec2:DescribeTransitGatewayAttachments",
                "ec2:GetTransitGatewayMulticastDomainAssociations"
            ]
        },
        "delete": {
            "permissions": [
                "ec2:DisassociateTransitGatewayMulticastDomain"
            ]
        },
        "list": {
            "permissions": [
                "ec2:DescribeTransitGatewayAttachments",
                "ec2:GetTransitGatewayMulticastDomainAssociations"
            ]
        }
    }
}

cli version: 2.0.0

**Comment by ammokhov** [comment]
> {
> "typeName": "AWS::EC2::TransitGatewayMulticastDomainAssociation",
...
> cli version: 2.0.0

could you change 
```json
"SubnetIds": {
    "description": "The IDs of the subnets to associate with the transit gateway multicast domain.",
    "type":"array",
    "contains": {
        "type": "string"
    }
}
```
===>

```json
"SubnetIds": {
    "type": "array",
    "items": {
        "type": "string"
    }
}
```
