### ISSUE TITLE
cfn submit error: An error occurred (IncompleteSignature) when calling the CreateStack operation

### ISSUE THREAD

**Issue by suhaniladani** [aws-cloudformation/cloudformation-cli#567]
An error occurred (IncompleteSignature) when calling the CreateStack operation: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'export'

**Comment by PatMyron** [comment]
Unfortunately, this repository is specifically for issues with the [CloudFormation Registry CLI](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/), not [CloudFormation's AWS CLI commands](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/index.html)

---

found some similar existing issues:
https://stackoverflow.com/questions/50873219/aws-credential-must-have-exactly-5-slash-delimited-elements
https://github.com/boto/boto3/issues/1752
https://github.com/mitchellh/vagrant-aws/issues/361
https://forums.aws.amazon.com/thread.jspa?threadID=191691

but recommend raising a support case for this issue at https://console.aws.amazon.com/support/home if you're still stuck
