### ISSUE TITLE
[contract test] non exitent resource test

### ISSUE THREAD

**Issue by ammokhov** [aws-cloudformation/cloudformation-cli#575]
```python
def contract_update_non_existent_resource(resource_client):
    create_request = resource_client.generate_invalid_create_example()
    update_request = resource_client.generate_update_example(create_request)
```

create request takes data from invalid json, which is merged into update request; this is not robust as it relies that update inputs override all the invalid inputs and update request will have a valid data but with non-existent identifier;

this won't work all the time; specifically relying on generating a valid update from merging invalid request seems too risky; 

we have a couple of options:

*Option 1*
create a valid request from create inputs file merge it with update and then change primary id:
```python
    create_request = resource_client.generate_create_example()
    update_request = resource_client.generate_update_example(create_request)
    update_invalid_identifier = {**update_request, ** { "primaryIdentifier": "non-existent-identifier" }}
```
the problem is that we need to rely on either strategy to get primary identifier or get just that value directly from invalid json imputs

*Option 2*
1. create a resource
2. delete a resource
3. use identifier from create resource to update and assert not found

**Comment by jotompki** [comment]
this test should cover this case: https://github.com/aws-cloudformation/cloudformation-cli/blob/059b8586b23e246316479c5c36622aa9f041e986/src/rpdk/core/contract/suite/handler_delete.py#L75-L83

Any reason we have this duplication @anshikg ?

**Comment by anshikg** [comment]
> this test should cover this case:
> 
> https://github.com/aws-cloudformation/cloudformation-cli/blob/059b8586b23e246316479c5c36622aa9f041e986/src/rpdk/core/contract/suite/handler_delete.py#L75-L83
> 
> Any reason we have this duplication @anshikg ?

Hey John, The reason the ```contract_update_non_existent_resource``` was written to ensure we catch the invalid update case. Although, in theory the ```contract_delete_update``` can replace the above test it will not work for resources which support soft delete. The ```contract_update_non_existent_resource``` ensures this specific feature should pass for resources with soft delete.

Hey Anton,
Could you please explain to me what is risky in merging the invalid and valid model in a temp variable?

**Comment by anshikg** [comment]
> ate a valid request from create inputs file merge it with update and then

Why is option 1 better than what we are doing now? This will add an additional feature on our end to figure out what a an acceptable value for the primary identifier is.

Option 2 seems better. Although, I am still unsure what this change is giving us. What happens when a resource supports soft delete?

**Comment by anshikg** [comment]
Closing this issue. Feel free to re-open this issue if this is still a concern.
