### ISSUE TITLE
[contract test] Drift parity

### ISSUE THREAD

**Issue by anshikg** [aws-cloudformation/cloudformation-cli#580]
Currently in contract test we compare if the input to a handler is equal to out for create and update handlers. This functionality check needs to be modified to work similar to Drift detection.

- [x] In drift, if a handler input does not contain a property but the output has the property set the resource is not drifted. We should maintain the same functionality in contract test.

- [x] In drift, if a resource has a list and it does not care about the order of the list we can add ```insertionOrder``` flag and this allows the drift to pass. 

Contract test need to have same functionality to ensure the un ordered list resources pass the contract test.

**Comment by prerna-p** [comment]
About #1, isn't this just handled by [these pruning steps](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/suite/handler_commons.py#L150-L159)?

**Comment by roolerzz** [comment]
On the similar lines, does the output of Create Handler also needs to match field by field to the model returned by the read handler?(for e.g. The current behavior I am seeing with our service is say the model returned by Create has fields A, B, C which was set in the create input, but the backend resource created has the attributes A, B, C, D, E(D & E being the defaults.)).
Now when the read handler runs, it fetches the state of the resource from the backend and populates and returns a model having the attributes(A, B, C, D, E)(Read won't necessarily remember what the inputs were to create.) Seems like some of the contract tests seem to fail validating asserting output of create(A, B, C) should be equal to output of Read(A, B, C, D, E). 

Q: Should there be this expectation that model output of CREATE should be deep equals to model output of READ, or similar to the drift you mentioned above, the system should support extra attributes in the model output of READ?
