### ISSUE TITLE
In which situation the LIST operation is called?

### ISSUE THREAD

**Issue by fsenart** [aws-cloudformation/cloudformation-cli#586]
CREATE and UPDATE operations are called whenever a stack is created/updated. The READ operation is called during stack imports. But I can't figure out when the LIST operation is called? Is this a placeholder operation for upcoming CloudFormation APIs, or I'm missing something?

**Comment by PatMyron** [comment]
Believe [AWS Config will be using CloudFormation ListHandlers](https://aws.amazon.com/about-aws/whats-new/2020/06/aws-config-integrates-aws-cloudformation-registry/). Think CloudFormation has additional future plans for ListHandlers as well
