### ISSUE TITLE
Readonly properties changing on update causing contract tests to fail

### ISSUE THREAD

**Issue by privetjr** [aws-cloudformation/cloudformation-cli#609]
### Motivation for Change
When running contract tests for a resource that has a read-only property that is modified automatically during an update, `contract_update_read_success` and `contract_update_list_success` contract tests fail with:

"AssertionError: All properties specified in the request MUST be present in the model returned, and they MUST match exactly, with the exception of properties defined as writeOnlyProperties in the resource schema"

See [the source here](https://github.com/aws-cloudformation/cloudformation-cli/blob/009e0965d32f51ce94f84af2c5a33698273bc515/src/rpdk/core/contract/suite/handler_commons.py#L149-L176)

Read-only properties that change automatically(e.g. a timestamp for when the resource was last updated) should not need to match. CloudFormation is not able to modify/write the property, but that doesn't mean read-only properties never change. The `test_input_equals_output` method should also prune read-only properties.

**Comment by anshikg** [comment]
Closing this issue as the code has been merged. Feel free to reopen this issue if I have missed something.
