### ISSUE TITLE
Rate exceeded (Service: AmazonCloudFront; Status Code: 400; Error Code: Throttling

### ISSUE THREAD

**Issue by mikezang** [aws-cloudformation/cloudformation-cli#611]
Description:

Steps to reproduce the issue:

1. I create a LambdaEdgae with CloudFront and S3 with template
2. if I set TrustedSigners to self and run `aws cloudformation deploy`, LambdaEdge function, s3 bucket and cloudfront are created without any problems
![behaviorsOK](https://user-images.githubusercontent.com/1030268/97778217-1333e580-1bb9-11eb-9349-10f3b88ac080.jpg)
3. I if only change TrustedSigners to key group what I defined on cloudfront console and run the same `aws cloudformation deploy`,
![keygroup jog](https://user-images.githubusercontent.com/1030268/97778238-42e2ed80-1bb9-11eb-906e-b4134a8232af.JPG)

Observed result:
I got error as below:
> Rate exceeded (Service: AmazonCloudFront; Status Code: 400; Error Code: Throttling; 
    
Expected result:
Here is what I set manual on CloudFront console
![behaviorsKeyGroup](https://user-images.githubusercontent.com/1030268/97778254-5b530800-1bb9-11eb-8bca-35835361930a.jpg)

Is this a bug? how can I use key group in cloudformation to deploy coudfront?

**Comment by PatMyron** [comment]
Unfortunately, this repository is specifically for issues with the [CloudFormation Registry CLI](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/)

You may want to raise a support case for this issue at https://console.aws.amazon.com/support/home
