### ISSUE TITLE
cfn init lists multiple entries of the java plugin

### ISSUE THREAD

**Issue by omkhegde** [aws-cloudformation/cloudformation-cli#616]
Using latest cfn version, when running the `cfn init` command, it results multiple entries for Java when selecting language for code generation (please see attached image). The issue seems to be caused by a recent change that fetches plugin choices during runtime: https://github.com/aws-cloudformation/cloudformation-cli/blob/67778ab7c42bf3cbb1d8126edf1b9b73e0c36c4c/src/rpdk/core/plugin_registry.py#L9

![Screen Shot 2020-11-04 at 12 48 24 PM](https://user-images.githubusercontent.com/69654230/98166388-2e923f80-1e9c-11eb-9201-9c587d74d29f.png)

**Comment by jotompki** [comment]
see if changing `sorted() to sorted(set())` fixes
