### ISSUE TITLE
Fix multi assignment across all handler contract tests

### ISSUE THREAD

**Issue by prerna-p** [aws-cloudformation/cloudformation-cli#629]
` request = input_model = model = resource_client.generate_create_example()` - handler_create.py
` create_request = input_model = model = resource_client.generate_create_example()` - handler_update.py
... and so on
I suspect these result in side effects that cause some contract tests to fail for our customers. They also affect code-readability.

**Comment by anshikg** [comment]
Could you elaborate on the proposal @prerna-p ?

**Comment by prerna-p** [comment]
Specifically S3::StorageLens was facing an issue due to this, however I have not heard back from them. I will reopen this when they get back
