### ISSUE TITLE
Validation failed while creating new module

### ISSUE THREAD

**Issue by vennemp** [aws-cloudformation/cloudformation-cli#638]
I literally was just following the steps in the aws module blog and got the following error:

```
Failed to register the type with registration token '99345c1e-73c5-4b3d-b15f-2fbaf605354a'.
Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [99345c1e-73c5-4b3d-b15f-2fbaf605354a] There should be only one valid json or yaml module fragment file under `fragments`.', 'ResponseMetadata': {'RequestId': '2647daf2-48ff-436b-a078-35bf445eb0ff', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '2647daf2-48ff-436b-a078-35bf445eb0ff', 'content-type': 'text/xml', 'content-length': '657', 'date': 'Fri, 27 Nov 2020 20:22:46 GMT'}, 'RetryAttempts': 0}}'
```

I followed the steps exactly.
Just ran:

cfn init
cfn submit

**Comment by vennemp** [comment]
cfn --version
cfn 0.2.1

**Comment by benbridts** [comment]
@vennemp What's in your `fragments` folder (`ls -A fragments`). Did you remove `sample.json` after creating `s3.json`?

**Comment by vennemp** [comment]
Yes. It was just that s3.json file and then the rdpk log file after it ran

**Comment by benbridts** [comment]
Do you mind sharing the zip that was created? It should be in a bucket called `cloudformationmanageduploadinfrast-artifactbucket-$RANDOMID`.

**Comment by vennemp** [comment]
[fti-s3-bucket-module-2020-11-27T20-22-15.zip](https://github.com/aws-cloudformation/cloudformation-cli/files/5611350/fti-s3-bucket-module-2020-11-27T20-22-15.zip)

**Comment by benbridts** [comment]
Does it work if you remove rpdk.log from the fragments folder? It looks like you ran one of the `cfn` commands from within the fragments folder, and the extra file might be causing this?

**Comment by vennemp** [comment]
That did it!
