### ISSUE TITLE
Error: Waiter TypeRegistrationComplete failed on cfn submit

### ISSUE THREAD

**Issue by toddlers** [aws-cloudformation/cloudformation-cli#639]
Hi,

I am using this[1] template as a starter while following this[2] blogpost. While running submits I am getting the following error:

```shell
❯❯ cfn submit -v --region us-east-1
Validating your module fragments...
Creating CloudFormationManagedUploadInfrastructure
CloudFormationManagedUploadInfrastructure stack was successfully created
Successfully submitted type. Waiting for registration with token '7fdadab3-d68d-4d4d-b3a0-06bd6a' to complete.
Failed to register the type with registration token '7fdadab3-d68d-4d4d-b3a0-06bd6a'.
Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [7fdadab3-d68d-4d4d-b3a0-06bd6a] There should be only one valid json or yaml module fragment file under `fragments`.', 'ResponseMetadata': {'RequestId': 'fd5690b2-f9fa-4555-bb30-145dac24d019', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'fd5690b2-f9fa-4555-bb30-145dac24d019', 'content-type': 'text/xml', 'content-length': '657', 'date': 'Sun, 29 Nov 2020 17:17:31 GMT'}, 'RetryAttempts': 0}}'
=== Caught downstream error ===
Waiter TypeRegistrationComplete failed: Waiter encountered a terminal failure state
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
``` 

Running follow environment

```txt
Python 3.9.0
cloudformation-cli               0.2.1
cloudformation-cli-python-plugin 2.1.2
boto3                            1.16.18
botocore                         1.19.18
```

I checked the stack to created fine but in the registration phase, I got the error. I double-checked my permissions before running this.

[1]https://github.com/aws-cloudformation/aws-cloudformation-samples/blob/main/modules/S3BucketBlog/fragments/s3.json
[2]https://aws.amazon.com/blogs/mt/introducing-aws-cloudformation-modules/

**Comment by benbridts** [comment]
@toddlers Can you double-check that there is only one file in the fragments folder (in  this case `s3.json`)?
Even if other files in that folder are not json/yaml, CloudFormation Registery will complain

**Comment by toddlers** [comment]
@benbridts  thanks for the quick response I double-checked that, as I mentioned in the bug report I am using the standard example by following the post.

**Comment by benbridts** [comment]
That's strange, the error message seems to imply that what you're seeing locally is different from what CloudFormation sees

Do you mind sharing the zip that was created? It should be in a bucket called `cloudformationmanageduploadinfrast-artifactbucket-$RANDOMID`.

**Comment by toddlers** [comment]
@benbridts thanks much for following up on this. I actually found the issue, I was using vscode and `.vscode` folder  got bundled with the package. When I did everything from the terminal it worked out fine. Checking the zip file in S3 bucket gave me the hint. Thanks,  closing this issue now.
