### ISSUE TITLE
Feature request: Check the files in the fragments folder before uploading

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-cli#640]
It's very easy to have an extra file in the fragments folder by accident (see #638, #639).

Since it seems that the CloudFormation Registry does not support more than 1 file in the fragments folder (even if the extra file is not ending in `.yaml`, `.json` or `.template`), it would help if the cloudformation-cli could throw an error or warning when there is more than one file present.

I quickly looked at the code, and a check for the number of files [here](https://github.com/aws-cloudformation/cloudformation-cli/blob/0a965641648b7aec851e897739a8ace7106beb14/src/rpdk/core/project.py#L469) seems possible

**Comment by MalikAtalla-AWS** [comment]
Thank you for bringing up this issue Ben. I'm able to reproduce the problem.

**Comment by MalikAtalla-AWS** [comment]
Will be resolved in versions >= 0.2.6
