### ISSUE TITLE
Incorrect JSON Schema meta-schema

### ISSUE THREAD

**Issue by Relequestual** [aws-cloudformation/cloudformation-cli#650]
This commit https://github.com/aws-cloudformation/cloudformation-cli/commit/b344d20c61228ee7a3625e76bea220cc3a0dcfbb#diff-72dbf7bf63e19ca35862d238484f6e7def698b8f476bbc97e62d9fdaafcc632e

modified the JSON Schema meta-schema, which is now not correct.

This is now potentially misleading.

There are a number of other issues relating to https://github.com/aws-cloudformation/cloudformation-cli/blob/b344d20c61228ee7a3625e76bea220cc3a0dcfbb/src/rpdk/core/data/schema/README.md if anyone is willing to discuss.

**Comment by jotompki** [comment]
Thanks for the callout. We added this to support local development and it should not have been modified. Looking into the removal process. Would be curious to hear about the other issues related to the resource schema. If you'd like we can spin up a discussion on our schema repo https://github.com/aws-cloudformation/aws-cloudformation-resource-schema

**Comment by jotompki** [comment]
merged in #651. very open to talking over on our resource schema repo to figure out how best to use jsonschema/if there are any issues we can correct https://github.com/aws-cloudformation/aws-cloudformation-resource-schema

**Comment by Relequestual** [comment]
Hi @jotompki. Nice quick turn around!
JSON Schema draft 2019-09 introduced the notion of dialects and vocabularies.
Draft 2020-12 will be used fully in OpenAPI specification 3.1.

I don't have a LOT of time right now (hence logging only a single small issue).
But, I may be available for some consultancy work on this in the new year, if that sounds viable for you.

If that's something that might be of interest, you can find my email on the spec documents in the author listing, or here: https://datatracker.ietf.org/doc/draft-bhutton-json-schema/

**Comment by PatMyron** [comment]
This is the only other part I could find where the JSON Schema meta-schema diverged, think we can remove that as well:
https://github.com/aws-cloudformation/cloudformation-cli/blob/5724de458760855ec797b9cb7b0b7411198f6ef0/src/rpdk/core/data/schema/meta-schema.json#L78-L81

**Comment by PatMyron** [comment]
This is the only other part I could find where the JSON Schema meta-schema diverged:

The version in [`resource-schema`](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/blob/master/src/main/resources/schema/schema) is missing:

https://github.com/aws-cloudformation/cloudformation-cli/blob/5724de458760855ec797b9cb7b0b7411198f6ef0/src/rpdk/core/data/schema/meta-schema.json#L78-L81

**Comment by Relequestual** [comment]
Good spot. There's probably milage in just flat out replacing with the meta-schemas just in case anything else has been missed.
