### ISSUE TITLE
Request: allow for `cfn submit` without running contract tests

### ISSUE THREAD

**Issue by ChoiByungWook** [aws-cloudformation/cloudformation-cli#684]
Hello,

Would it be possible to allow for submitting to register a CloudFormation resource without invoking contract tests?

I understand the [register-type](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/register-type.html) API doesn't allow for skipping the contract test, so I imagine this would require a change in the internal system. Perhaps the flag can default to True.

The reason for this request is, I noticed that my registrations can take a while to finish (10 minutes) and I believe it might be due to contract tests being run.

I would love if I can register my private resource quickly with a command such as

```
cfn submit --contract-tests false
```

so that it would allow for fast debugging on my end.

Thanks!

**Comment by anshikg** [comment]
Hi @ChoiByungWook 
Contract test is a required feature for submitting the resource. As of now, publishing a resource through cfn submit does not block registration even if contract test fail. But, we will start failing registration if contract test fail. 
Therefore, we can not run cfn submit without contract test.
