### ISSUE TITLE
Contract tests misbehave on schemas with required write-only properties

### ISSUE THREAD

**Issue by micahduron** [aws-cloudformation/cloudformation-cli#685]
Because contract tests sometimes directly pass a handler's output model as the input model to another handler invocation, it can cause handlers to fail with model validation errors when a resource's schema contains required write-only properties.

**Comment by anshikg** [comment]
Could you please share an example of the issue you seeing. This would help me understand what case is failing for you.

**Comment by anshikg** [comment]
Checked with the dev. He was using an older version of the cli. Upgrading the cli go rid of the issue
