### ISSUE TITLE
cfn init - fails with pkg VersionConflict

### ISSUE THREAD

**Issue by asantos-fuze** [aws-cloudformation/cloudformation-cli#727]
Hi,

I get the following error when trying to run cfn init
```
Traceback (most recent call last):
  File "/home/ec2-user/cfn-cli/lib64/python3.7/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/home/ec2-user/cfn-cli/lib64/python3.7/site-packages/rpdk/core/init.py", line 166, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/home/ec2-user/cfn-cli/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/home/ec2-user/cfn-cli/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/ec2-user/cfn-cli/lib64/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (docker 5.0.0 (/home/ec2-user/cfn-cli/lib/python3.7/site-packages), Requirement.parse('docker<5,>=3.7'))
```

## Installation steps
**AMI:** amzn2-ami-hvm-2.0.20210326.0-x86_64-gp2

```
sudo yum install python3 -y
sudo amazon-linux-extras install docker -y
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user
wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
sudo ./sam-installation/install
python3 -m venv cfn-cli
source cfn-cli/bin/activate
python -m pip install cloudformation-cli cloudformation-cli-python-plugin
```

During the python pkg installation it is visible the error `ERROR: cloudformation-cli-python-plugin 2.1.2 has requirement docker<5,>=3.7, but you'll have docker 5.0.0 which is incompatible.`

**Comment by benbridts** [comment]
Stupid suggestion, but does it work if you install `cloudformation-cli-python-plugin` first?

It seems like you're doing the right thing to avoid having docker already in the virtualenv

**Comment by asantos-fuze** [comment]
Hi @benbridts 
I've just lunched an new EC2 instance and replayed all the steps except `python -m pip install cloudformation-cli cloudformation-cli-python-plugin`

I've tested what you've suggested:

```
python -m pip install cloudformation-cli
python -m pip install cloudformation-cli
```

And it worked.

The workaround I've done previously was to downgrade some of the pkgs.

```
python -m pip uninstall docker
python -m pip install -I docker==4.4.4
python -m pip uninstall urllib3
python -m pip install -I urllib3==1.25.11
```

**Comment by benbridts** [comment]
@PatMyron It might be worth looking at the requirements for cloudformation-cli  and the plugins and try to keep them with the same version definition (either limiting cloudformation-cli's docker to <5.0, or allowing docker >5.0 in the python plugin)

**Comment by asantos-fuze** [comment]
@PatMyron There is clearly an issue here. Installing cfn-cli per the info in the README file does not work. I'd suggest a fix in the requirements, or on the docs

**Comment by PatMyron** [comment]
@asantos-fuze that command works in a fresh Python environment, but unfortunately, existing Python environment dependencies can be outside dependency version ranges. I'm not sure why the plugins pin `docker` stricter than `cloudformation-cli`, so I think it's probably best to remove the restriction from the plugins
