### ISSUE TITLE
`additionalIdentifiers` in schema cause update example generation failure.

### ISSUE THREAD

**Issue by ptrucks** [aws-cloudformation/cloudformation-cli#731]
When generating an update example for contract tests, the resource client looks up unique keys from the resource model, however if there are `additionalIdentifiers` the check (see [here](https://github.com/aws-cloudformation/cloudformation-cli/blob/a143ded46fe47690884eb1fb91659e3df396e3f5/src/rpdk/core/contract/resource_client.py#L420)) will fail when passing a set of tuples to [`fragment_list`](https://github.com/aws-cloudformation/cloudformation-cli/blob/a143ded46fe47690884eb1fb91659e3df396e3f5/src/rpdk/core/jsonutils/pointer.py#L100) which will try to call `split` on each tuple in the set, rather than on each string in the tuple for a correct input.

It looks like there is no test case for a schema with `additionalIdentifiers`, so this was not caught.

I will create a PR to fix this issue if that would be accepted.

**Comment by ptrucks** [comment]
I opened a PR to fix the problematic check [here](https://github.com/aws-cloudformation/cloudformation-cli/pull/732).

**Comment by anshikg** [comment]
Closing the issue as the code change has been pushed
