### ISSUE TITLE
Are contract tests supposed to be able to handle {{resolve}} as values?

### ISSUE THREAD

**Issue by SHxKM** [aws-cloudformation/cloudformation-cli#735]
With this input to `inputs_1_create.json`:

```json
{
  "credentials": {
    "accessToken": "{{resolve:secretsmanager:secretname:SecretString:secertkeyname}}",
    "accountId": "someStringHere"
  },
...
}
```

I get:

```
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
```

Unfortunately I cannot share this file. But I can see this in it:

```
Traceback (most recent call last):
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/rpdk/core/test.py", line 192, in test
    inputs = get_inputs(
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/rpdk/core/test.py", line 150, in get_inputs
    overrides_raw = render_jinja(
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/rpdk/core/test.py", line 76, in render_jinja
    parsed_content = env.parse(overrides_string)
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 535, in parse
    self.handle_exception(source=source)
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/myusername/.virtualenvs/myenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 3, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
```

What am I doing wrong?

I see that the error is coming from jinja where `{{ }}` are special characters denoting a variable. If so, how are we expected to hold a public repository which refers to confidential information stored in secrets-manager and needs to override test inputs with such information?

**Comment by anshikg** [comment]
@PatMyron Actually, dynamic references are supported in contract test inputs: https://github.com/aws-cloudformation/cloudformation-cli/blame/811163009f679724a1812807901e1b3cdade37f6/src/rpdk/core/test.py#L150-L152

@SHxKM could you share the template which creates the 'accessToken' value which is injected in the above example?

**Comment by SHxKM** [comment]
> @PatMyron Actually, dynamic references are supported in contract test inputs: https://github.com/aws-cloudformation/cloudformation-cli/blame/811163009f679724a1812807901e1b3cdade37f6/src/rpdk/core/test.py#L150-L152
> 
> @SHxKM could you share the template which creates the 'accessToken' value which is injected in the above example?

@anshikg can you clarify what you mean by “the template which creates the ‘accessToken’”? accessToken is a token pre-saved by my clients in secretsmanager, and when they create a stack using my custom type, they give the special {{resolve:}} notation as the value.

**Comment by PatMyron** [comment]
@anshikg believe those are [CloudFormation exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) as described in https://github.com/aws-cloudformation/cloudformation-cli/pull/411, not [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html)

**Comment by PatMyron** [comment]
the solution to https://github.com/aws-cloudformation/cloudformation-cli/issues/630 might help with this once there's a solution for that

**Comment by SHxKM** [comment]
Still looking for a solution to this. I’ve seen some examples using a special (?) file with an  _exports naming convention, anyone knows if this should work? There is no documentation whatsoever on this and Googling doesn’t yield any results.

https://github.com/aws-quickstart/quickstart-helm-resource-provider/blob/main/contract_test_exports.template.yaml

**Comment by PatMyron** [comment]
> seen some examples using a special (?) file with an _exports naming convention, anyone knows if this should work?

file name itself isn't special, believe that's just [CloudFormation exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) as described in https://github.com/aws-cloudformation/cloudformation-cli/pull/411 as mentioned earlier

**Comment by SHxKM** [comment]
Interesting. Presumably I could store said credentials in secretsmanager, export it in the template, and then use that export value. Does that make sense? Or does this only work for values that are generated on every build?

if nothing is special about the file name, where in the build/package process is this run? Meaning how can I point to this file when running `cfn test` (locally and remotely)?

**Comment by PatMyron** [comment]
> if nothing is special about the file name, where in the build/package process is this run? Meaning how can I point to this file when running `cfn test` (locally and remotely)?

unfortunately, not automatically deployed by `cloudformation-cli` yet. CloudFormation stack with exports needs to be deployed separately first before running `cfn-test` as of now

> do I even want to export a sensitive token from a CFN template

don't recommend this

**Comment by SHxKM** [comment]
Thanks Pat. So still waiting for a better solution. 

For now we’re deploying the .zip handler with the tokens inside, revoking them immediately after passing the tests, and using pre-commit hooks to prevent anything leaking to the repository.

**Comment by cmgorton** [comment]
Hey @SHxKM. We are working on answering and cleaning up stale issues. 

If this is still an unanswered question for you, please feel free to reopen this issue so we can investigate it further. 

You can also ask questions in our [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) channel for a more prompt response.
