### ISSUE TITLE
=== Unhandled exception === mapping values are not allowed here

### ISSUE THREAD

**Issue by JasonWainwright777** [aws-cloudformation/cloudformation-cli#744]
[rpdk.log](https://github.com/aws-cloudformation/cloudformation-cli/files/6401053/rpdk.log)

[AutoScalingGroup.yml.txt](https://github.com/aws-cloudformation/cloudformation-cli/files/6401060/AutoScalingGroup.yml.txt) Appear to be having issues with standard cloudformation usage.

**Comment by JasonWainwright777** [comment]
On further review it appears to be the use of mappings to dynamicaly post the region

**Comment by JasonWainwright777** [comment]
I does not appear to be the Findinmap function. It appears to be the way I am using the Sub function to set a variable mapping.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

**Comment by PatMyron** [comment]
similar to https://github.com/aws-cloudformation/cfn-python-lint/issues/630

**Comment by MalikAtalla-AWS** [comment]
Hey @JasonWainwright777 
thank you for raising this issue.

I tried creating a module with the file you linked and I got the error:
`Invalid template fragment: Template fragment cannot contain any Export. Found an Export statement in Output: AppAsg`

After removing the export from the template, I don't get any more error messages (only linter warnings)

Can you give us the exact commands you ran? Is the file you linked up to date with the one that reproduces the issue? Also, which version of the cfn-cli are you using? (run `cfn --version`)

**Comment by MalikAtalla-AWS** [comment]
I'll close this issue as I haven't heard back. Feel free to reopen if the issue persists.
