### ISSUE TITLE
 Unhandled exception when running 'cfn test'

### ISSUE THREAD

**Issue by askthoma** [aws-cloudformation/cloudformation-cli#761]
Seen in terminal: 

`> cfn test                                                                                                                                                                                      13:34
Resource schema is valid.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'`

Seen in logs: 

```python
[2021-05-17T20:36:32Z] DEBUG    - Override file '/Users/askthoma/workplace/senate_cfn_test/src/AWSCloudFormationResourceProvidersIoTCoreDeviceAdvisor/aws-iotcoredeviceadvisor-suitedefinition/overrides.json' not found. No overrides will be applied
[2021-05-17T20:36:32Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/test.py", line 192, in test
    inputs = get_inputs(
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/test.py", line 150, in get_inputs
    overrides_raw = render_jinja(
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/test.py", line 91, in render_jinja
    to_return = json.loads(overrides_string)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 754)
```

**Comment by PatMyron** [comment]
Do you have an [`inputs`](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test.html#resource-type-test-input-data) directory? If so, do you mind sharing the contents?

**Comment by askthoma** [comment]
I have 3 files in that directory. 

`> cat inputs_1_create.json                                                                                                    
{
    "SuiteDefinitionConfiguration": {
        "DevicePermissionRoleArn": "arn:aws:iam::633921871730:role/DeviceAdvisorRole",
        "IntendedForQualification": false,
        "Devices": [{"ThingArn":"arn:aws:iot:us-east-1:633921871730:thing/DeviceAdvisorThing3"}],
        "RootGroup": "{\"configuration\":{},\"tests\":[{\"id\":\"04f68b01-3c4c-4c1c-a1d4-0fd9ff1d62c0\",\"name\":\"TestGroup\",\"configuration\":{\"EXECUTION_TIMEOUT\":\"300000\"},\"tests\":[{\"id\":\"e97e3142-cf08-4b0a-9b51-693207ff36e7\",\"name\":\"MQTTPublishTest\",\"configuration\":{\"TOPIC_FOR_PUBLISH_VALIDATION\":\"target\"},\"test\":{\"id\":\"MQTT_Publish\",\"testCase\":null,\"version\":\"0.0.0\"}}]}]}",
        "SuiteDefinitionName": "contract-test-suite-definition"
    },
}`


`> cat inputs_1_invalid.json                                                                                                    
{
    "SuiteDefinitionConfiguration": {
        "IntendedForQualification": false,
        "SuiteDefinitionName": "contract-test-suite-definition"
    }
}`


`> cat inputs_1_update.json                                                                                                   
{
    "SuiteDefinitionConfiguration": {
        "DevicePermissionRoleArn": "arn:aws:iam::633921871730:role/DeviceAdvisorRole",
        "IntendedForQualification": false,
        "Devices": [],
        "RootGroup": "{\"configuration\":{},\"tests\":[{\"id\":\"ccc41a73-4337-49c6-ab71-392cc078ab72\",\"name\":\"TestGroup\",\"configuration\":{\"EXECUTION_TIMEOUT\":\"100000\"},\"tests\":[{\"id\":\"e97e3142-cf08-4b0a-9b51-693207ff36e7\",\"name\":\"MQTTConnectTest\",\"configuration\":{},\"test\":{\"id\":\"MQTT_Connect\",\"testCase\":null,\"version\":\"0.0.0\"}}]}]}",
        "SuiteDefinitionName": "contract-test-suite-definition"
    }
}`

**Comment by PatMyron** [comment]
believe the trailing comma in `inputs_1_create.json` might be causing the `JSONDecodeError`

**Comment by askthoma** [comment]
Yeah that fixed my problem, thank you.
