### ISSUE TITLE
Increase Timeouts for tests

### ISSUE THREAD

**Issue by SHxKM** [aws-cloudformation/cloudformation-cli#780]
We often have to run the same test a few times. It will eventually pass but we are getting multiple READ timeouts almost on each (local) full suite run.

Our handler code is in Java if that matters.

**Comment by PatMyron** [comment]
[timeout can be raised locally btw](https://github.com/aws-cloudformation/cloudformation-cli#command-test):

`cfn test --enforce-timeout 240`

---

([PR to change the default](https://github.com/aws-cloudformation/cloudformation-cli/pull/554))

**Comment by SHxKM** [comment]
Although it looks like this can't be used with other options like `tb-long`, etc..
