### ISSUE TITLE
Unable to submit module

### ISSUE THREAD

**Issue by MatteoGioioso** [aws-cloudformation/cloudformation-cli#783]
I am trying to develop a simple module, but the `submit` command seems broken 

Steps to reproduce

1. `cfn init`
2. write `.yaml` template insde the `fragments/` folder
3. run `cfn validate` => `Module fragment is valid`
4. run `cfn-lint` => all good
5. run `cfn submit --dry-run` all good
5. run `cfn submit`

```
Module fragment is valid.
Successfully submitted type. Waiting for registration with token '*****' to complete.
Failed to register the type with registration token '*****'.
Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with error. Error message: [****] Error validating module fragment and schema definition: malformed module fragment found AWSTemplateFormatVersion: "2010-09-09"\nDescription: >\n  This template deploys a VPC in two AZs\n\nParameters:\n  ....


...', 'TypeArn': 'arn:aws:cloudformation:us-east-1:000000000000:type/module/Name-VPC-2AZS-MODULE', 'TypeVersionArn': 'arn:aws:cloudformation:us-east-1:00000000:type/module/Hirvitek-VPC-2AZS-MODULE/00000001', 'ResponseMetadata': {'RequestId': *********', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '******', 'content-type': 'text/xml', 'content-length': '1657', 'date': 'Sat, 12 Jun 2021 10:37:16 GMT'}, 'RetryAttempts': 0}}'
=== Caught downstream error ===
Waiter TypeRegistrationComplete failed: Waiter encountered a terminal failure state: For expression "ProgressStatus" we matched expected path: "FAILED"
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
```
This error is quite vague and I cannot really tell what is going on, maybe `.yaml` is not supported?

6. Trying to deploy this through Cloudformation worked as well

My cli version
```
cfn 0.2.12
```

**Comment by MatteoGioioso** [comment]
I will post the full template, I have tried with a minimal one and it worked: https://github.com/hirvitek/aws-iac/blob/master/vpc/vpc2AZS/fragments/vpc-2azs.yaml

**Comment by MalikAtalla-AWS** [comment]
Hi Matteo, as a result of this issue we have made a change to better expose error messages from parsing modules. (The commit is in an internal code package, not here). It's not in production yet, but I can send a note here once it's available. Thanks again for raising this issue.

**Comment by MalikAtalla-AWS** [comment]
The change to expose parsing errors to the cli user is deployed to production. You should now be pointed to the specific error.

**Comment by MalikAtalla-AWS** [comment]
Let me know if this works @MatteoGioioso.
