### ISSUE TITLE
cloudformation cli version 0.2.13 issue

### ISSUE THREAD

**Issue by sriram9707** [aws-cloudformation/cloudformation-cli#791]
Hi,

we have been facing issue while submitting the modules with this version. this version expects the module templates files in fragments and as well as in the root directory. Earlier versions fetches the modules file from fragments folder alone.

**Comment by MalikAtalla-AWS** [comment]
Hi, thank you for raising this issue. Can you give us more detail to help us reproduce the issue? What is the exact folder structure you have. Would you mind sharing the relevant contents of the log file?

**Comment by MalikAtalla-AWS** [comment]
Hi @sriram9707 . This issue should be resolved in the latest version of the cli
https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.2.16
