### ISSUE TITLE
Unable to submit module

### ISSUE THREAD

**Issue by Sushant-Keny** [aws-cloudformation/cloudformation-cli#793]
I'm trying to create a module to experiment AWS CloudFormation Modules.

These are the following commands:

- `cfn init`
- `cfn submit`

**Output**
Module fragment is valid.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'

**Logs**
`[2021-06-29T06:31:16Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "c:\users\xyz\appdata\local\programs\python\python39\lib\site-packages\rpdk\core\cli.py", line 100, in main
    args.command(args)
  File "c:\users\xyz\appdata\local\programs\python\python39\lib\site-packages\rpdk\core\submit.py", line 15, in submit
    project.submit(
  File "c:\users\xyz\appdata\local\programs\python\python39\lib\site-packages\rpdk\core\project.py", line 502, in submit
    zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME)
  File "c:\users\xyz\appdata\local\programs\python\python39\lib\zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "c:\users\xyz\appdata\local\programs\python\python39\lib\zipfile.py", line 501, in from_file
    st = os.stat(filename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Training\\CloudFormation Modules\\Code Bundle\\S3 Bucket\\s3-module\\rsrchexp-s3-bucket-module.json'
`

I have tried re-installing the CLI but it didn't work.

Note: I'm using Windows 10 operating system.

**Comment by revanthreddy36** [comment]
I am having similar issue. 
Attaching my rpdk.log to this comment

However, if I rename my schema.json to the file being not found, it works. 
Not sure if this has something to do with specifying the schema file

`2021-06-29T18:12:39Z] DEBUG    - Results from rule E1027 are []: 
[2021-06-29T18:12:39Z] DEBUG    - Get resources from template...
[2021-06-29T18:12:39Z] WARNING  - Module fragment is valid.
[2021-06-29T18:12:40Z] DEBUG    - Overwriting '/Users/revatumu/ec2-macos-module/schema.json'
[2021-06-29T18:12:40Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/submit.py", line 15, in submit
    project.submit(
  File "/usr/local/lib/python3.9/site-packages/rpdk/core/project.py", line 502, in submit
    zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1727, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 501, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/revatumu/ec2-macos-module/proserve-ec2-instance-module.json'`

**Comment by Sushant-Keny** [comment]
@revanthreddy36 CloudFormation module is created after renaming `schema.json`?

**Comment by rickschubert** [comment]
I am also seeing this issue now, when trying to run `cfn submit`.

Error output:

```
#!/bin/bash -eo pipefail
aws-role --role-arn="${IAM_DEPLOYMENT_ROLE}" cfn submit --set-default
Module fragment is valid.
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'
FATA[0006] Failed to run command                         command="[cfn submit --set-default]" error="exit status 127"
Exited with code exit status 1
```

Log file content:

```
[2021-06-30T09:42:15Z] WARNING  - Module fragment is valid.
[2021-06-30T09:42:15Z] DEBUG    - Overwriting '/root/project/modules/test-modules/ecs-service-v1/schema.json'
[2021-06-30T09:42:15Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/submit.py", line 21, in submit
    args.set_default,
  File "/usr/local/lib/python3.7/site-packages/rpdk/core/project.py", line 502, in submit
    zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME)
  File "/usr/lib64/python3.7/zipfile.py", line 1730, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/usr/lib64/python3.7/zipfile.py", line 518, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/project/modules/test-modules/ecs-service-v1/youview-test-ecsservicev1-module.json'
```

**Comment by whoDoneItAgain** [comment]
> I am having similar issue.
> Attaching my rpdk.log to this comment
> 
> However, if I rename my schema.json to the file being not found, it works.
> Not sure if this has something to do with specifying the schema file
> 
> `2021-06-29T18:12:39Z] DEBUG - Results from rule E1027 are []: [2021-06-29T18:12:39Z] DEBUG - Get resources from template... [2021-06-29T18:12:39Z] WARNING - Module fragment is valid. [2021-06-29T18:12:40Z] DEBUG - Overwriting '/Users/revatumu/ec2-macos-module/schema.json' [2021-06-29T18:12:40Z] DEBUG - Unhandled exception Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main args.command(args) File "/usr/local/lib/python3.9/site-packages/rpdk/core/submit.py", line 15, in submit project.submit( File "/usr/local/lib/python3.9/site-packages/rpdk/core/project.py", line 502, in submit zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME) File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1727, in write zinfo = ZipInfo.from_file(filename, arcname, File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 501, in from_file st = os.stat(filename) FileNotFoundError: [Errno 2] No such file or directory: '/Users/revatumu/ec2-macos-module/proserve-ec2-instance-module.json'`

I'm seeingt

> I am having similar issue.
> Attaching my rpdk.log to this comment
> 
> However, if I rename my schema.json to the file being not found, it works.
> Not sure if this has something to do with specifying the schema file
> 
> `2021-06-29T18:12:39Z] DEBUG - Results from rule E1027 are []: [2021-06-29T18:12:39Z] DEBUG - Get resources from template... [2021-06-29T18:12:39Z] WARNING - Module fragment is valid. [2021-06-29T18:12:40Z] DEBUG - Overwriting '/Users/revatumu/ec2-macos-module/schema.json' [2021-06-29T18:12:40Z] DEBUG - Unhandled exception Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/rpdk/core/cli.py", line 100, in main args.command(args) File "/usr/local/lib/python3.9/site-packages/rpdk/core/submit.py", line 15, in submit project.submit( File "/usr/local/lib/python3.9/site-packages/rpdk/core/project.py", line 502, in submit zip_file.write(self.schema_path, SCHEMA_UPLOAD_FILENAME) File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1727, in write zinfo = ZipInfo.from_file(filename, arcname, File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 501, in from_file st = os.stat(filename) FileNotFoundError: [Errno 2] No such file or directory: '/Users/revatumu/ec2-macos-module/proserve-ec2-instance-module.json'`

I'm seeing the same thing. after renaming the schema file, i can "sort of" run cfn submit --dry-run successfully but get a duplicate schema.json in the zip file.

![image](https://user-images.githubusercontent.com/12127434/123995467-5e96d180-d99c-11eb-9253-c549dfb66ccd.png)

**Comment by rickschubert** [comment]
We have found a fix for this now: We were using the tool `cloudformation-cli-python-plugin` for `cfn` and installing the cloudformation-cli using pip3 without a regular version. We now don't use the python plugin and set a specific version of the CLI like so:

```
pip3 install cloudformation-cli==0.2.12
```

At least in our case, this fixed it for us.

**Comment by mikebroberts** [comment]
I'm also seeing this - first attempt to create a module. Using Mac OS, and installed using `pip3 install cloudformation-cli-typescript-plugin` . Downgrading using @rickschubert 's suggestion appears to have worked (thanks Rick) . 

I strongly recommend fixing this since it's a blocker on first time user experience.

**Comment by MalikAtalla-AWS** [comment]
Thanks for everyone for raising this issue and providing a temporary workaround. We are working on a fix and will send an update here once it's available.

**Comment by ugudip** [comment]
Keeping this issue open till the deployment completes.
Re opening this issue as it was accidentally closed.

**Comment by ugudip** [comment]
New version of rpdk is launched, can you please upgrade the version and check now? https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.2.16

Keeping this issue open till we get a confirmation.

**Comment by mikebroberts** [comment]
@ugudip / @MalikAtalla-AWS  - This now works for me with 0.2.16 - thanks

**Comment by ugudip** [comment]
Great, thanks. Closing this issue.
