### ISSUE TITLE
Facing issues while running cfn init on cloudshell as well as on a EC2 instance in ap-south-1

### ISSUE THREAD

**Issue by KislayaSrivastava** [aws-cloudformation/cloudformation-cli#806]
Hi Team, 
I was trying to create a custom module for cloudformation registry. 

I installed the CLI on cloudshell with below command

`pip3 install cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin cloudformation-cli-typescript-plugin`

as soon as i am submitting cfn init I am getting below error

![image](https://user-images.githubusercontent.com/40534292/128820028-4b9ebadc-8ce0-47db-9cc7-87b2ed2ad769.png)

I tried the same after creating an EC2 instance on ap-south-1 and trying the same there. 

There i am not able to submit the module post creating a yaml file 

![ModuleCF_Error](https://user-images.githubusercontent.com/40534292/128820994-20e6a160-77d9-44af-a60e-52548c9910dd.PNG)

The log file is at this location

[https://mytestcrrbucket.s3.ap-south-1.amazonaws.com/rpdk.log](url)

Please help in decoding this issue.

**Comment by virtualdiablo** [comment]
I have had the same issue in us-east-1

**Comment by MalikAtalla-AWS** [comment]
Hey @KislayaSrivastava I don't have access to the file you shared above. Would you mind sharing the rpdk.log again?

**Comment by MalikAtalla-AWS** [comment]
Tracking this internally under ticket id: P59055002

**Comment by lejiati** [comment]
Hi @KislayaSrivastava @virtualdiablo,

Thanks for raising this issue. I have reproduced this error in us-east-1 as well as us-west-2. Looks like CloudShell pre-installed some Python packages upon provisioning and package _six_ has version _1.14.0_ installed.

You can work around this issue by upgrading _six_ : `pip3 install --upgrade six` which should upgrade it to _1.16.0_. Once package is upgraded you can rerun `cfn init`.

Please let me know if you still have issues to create a module.
