### ISSUE TITLE
Contract tests fail on out-of-order collections when insertionOrder=false

### ISSUE THREAD

**Issue by osdrv** [aws-cloudformation/cloudformation-cli#811]
Hey folks,

I'm developing a resource where one of the attributes is an out-of-order collection (practically, a set). The service preserves no specific order on the items in this collection, hence I'm being explicit on setting `insertionOrder=false`:

```json
"Foo": {
  "type": "array",
  "insertionOrder": false,
  "items": {
    "$ref": "#/definitions/Foo"
  }
}
```

My CFN version:
```
cfn --version
cfn 0.2.15
```

My contract test input file declares this collection in a particular order. The service response model implies on no specific order returned.

When I run `cfn test`, I'm getting this error:
```
AssertionError: All properties specified in the request MUST be present in the model returned, and they MUST match exactly, with the exception of properties defined as writeOnlyProperties in the resource schema
```

The tool says nothing what specific object failed the validation, but from rpdk.log I see the order of the input and the response collections is distinct.

I checked the contract test executor code (https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/resource_client.py#L351) and it seems it doesn't respect `insertionOrder` attribute:

```python
351     def compare(self, inputs, outputs):
...
360                 for key in inputs:
...
363                     elif isinstance(inputs[key], list):
364                         assert len(inputs[key]) == len(outputs[key])
365                         self.compare_list(inputs[key], outputs[key])
...
373     def compare_list(self, inputs, outputs):
374         for index in range(len(inputs)):
375             self.compare(inputs[index], outputs[index])
```

Would you please assist on this case and let me know if this attribute would be supported by the tool in the future revisions?

Thank you.

**Comment by ammokhov** [comment]
Thanks for filing this issue, it looks that there is an assumption in the code that any collection has an order built-in. Fairly simple change, CFN will prioritize the work withing next couple of weeks. Feel free to contribute as well.

**Comment by ammokhov** [comment]
@osdrv PR is attached to the issue (#812) plz take a look at the change
