### ISSUE TITLE
Using a private API in jsonschema that has now been removed

### ISSUE THREAD

**Issue by kemitix** [aws-cloudformation/cloudformation-cli#830]
`core/jsonutils/renamer.py` [uses](https://github.com/aws-cloudformation/cloudformation-cli/blob/8473874f3cdcaef21552465c45b0d44e8c752d7c/src/rpdk/core/jsonutils/renamer.py#L3) the `jsonschema.compat` API which is a [private API](https://github.com/Julian/jsonschema/blob/3ececbd66dc8190287e7c9cd7c87387c637f1d19/jsonschema/compat.py#L4).

The new 4.0.0 and 4.0.1 versions of `jsonschema` removes that API.

ref: https://github.com/Julian/jsonschema/issues/843#issuecomment-931247200

**Comment by skinny85** [comment]
I just ran into this issue (the `cfn` command fails saying `jsonschema.compat` has not been found).

I can confirm @richardhboyd's workaround did make the problem go away for me, but this should definitely be fixed upstream.

**Comment by priyap286** [comment]
@richardhboyd 's PR to fix this is merged, #840. Closing this issue. Thanks Richard!

**Comment by priyap286** [comment]
The issue was raised with jsonschema, https://github.com/Julian/jsonschema/issues/843.

**Comment by kemitix** [comment]
Thanks for the stopgap @richardhboyd

**Comment by priyap286** [comment]
[v0.2.21](https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.2.21https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.2.21) has this fix.
