### ISSUE TITLE
Can build locally but CodeBuild check fails on submitting PR

### ISSUE THREAD

**Issue by lurayyy** [aws-cloudformation/cloudformation-cli#848]
I'm able to build on my laptop successfully using mvn. However, the CodeBuild check fails on submitting the PR with code build id "aws-cloudformation-resource-providers-lex-ci:18256b45-9dd8-41c5-a4f3-b4d1c3a874f8".

I have made the fix mentioned in this issue to add `-  pip install --upgrade 'six==1.15.0'` in buildspec.xml (https://github.com/aws-cloudformation/cloudformation-cli/issues/676) but the issue persist.

Attaching the build failed message here too:

```
COMMAND_EXECUTION_ERROR: Error while executing command: if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then cd $CODEBUILD_SRC_DIR # skip hidden folders dirs=$(find . -not -path "\./\.*" -mindepth 1 -maxdepth 1 -type d) echo "Folders to build: $dirs" for directory in $dirs; do cd "$directory" mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress if [ "$?" -ne 0 ] ; then echo "Build failed!" exit 1 else cd ".." fi done else echo "$CODEBUILD_SRC_DIR is empty" fi . Reason: exit status 1
```

**Comment by ammokhov** [comment]
this suggestion would definitely help debugging - https://github.com/aws-cloudformation/cloudformation-cli/issues/676#issuecomment-769255174

try something similar - https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2/blob/master/buildspec.yml#L7-L10

**Comment by lurayyy** [comment]
Thanks! The pyyaml upgrade did the trick `-  pip install pyyaml --upgrade`.
