### ISSUE TITLE
AWS::Serverless::Function with ImageUri doesn't use the updated image when the image is updated under the same imageTag

### ISSUE THREAD

**Issue by Jun711** [aws-cloudformation/cloudformation-cli#853]
I am not sure which of these three services:AWS Lambda / AWS CloudFormation / AWS Codepipeline that I configured incorrectly.
Could you please let me know which part I need to modify to make it work if this is not an expected behaviour? 
Thank you

**Info**
I have `AWS::Serverless::Function` that uses ImageUri and it is working as expected.
To update it, I have a buildspec file that does docker build, tag and push to ECR.
Codepipeline is used to do Source from CodeCommit, Build using CodeBuild and Deploy that consists of 'create or replace change set' and 'execute chang set'
When I modify my application and push the changes to CodeCommit, it can update the image on ECR but it doesn't update the Lambda. The error message that I see on the stack pipeline-changeset is `No updates are to be performed.`

On AWS console, I can see that ECR image is updated but lambda function is not. Lambda Function is set to use that same image with the same imageTag. 

I have the image and imageTag written in the buildspec file. It would be inconvenient if I have to change the imageTagName every time I make some changes. 

**Expected**
I expect it to update Lambda or make Lambda use the updated image even though the image is updated and tagged using the same imageTag.

**Comment by mircealam** [comment]
This is not the right place. Please verify if there is an issue here and if not please open one: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap

Also, when reporting the issue it helps if you can provide a bit more details to help replicate the issue (e.g. a minimal template that helps reproduce the issue can immensely help)
