### ISSUE TITLE
please add python 3.9 / 3.10 support

### ISSUE THREAD

**Issue by tbugfinder** [aws-cloudformation/cloudformation-cli#879]
Currently setup.py ends with python 3.8.
As python evolves this library should also "support" the installation and use within python 3.9/3.10.

**Comment by PatMyron** [comment]
related: https://github.com/aws-cloudformation/cloudformation-cli/pull/870

**Comment by mmaeng** [comment]
Should be resolved in the PR referenced above.

You can also ask questions in our [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) channel for a more prompt response.
