### ISSUE TITLE
Incorrect test inputs produced for RegEx word character

### ISSUE THREAD

**Issue by andrewbanchich** [aws-cloudformation/cloudformation-cli#883]
Specifying a pattern using a word character (e.g. `^[\w\-.~]+$`) causes invalid generated test inputs such as `ŏŏşNÇţā3MKÁŔßïõŜàĆXń²ńÖÞ`.

Replacing the above RegEx with `^[A-Za-z0-9_\-.~]+$` fixes this issue, so I assume that CFN CLI has a bug specifically related to `\w`.

**Comment by mmaeng** [comment]
This fix should resolve this as well.  Returning ASCII instead of unicode.

We are also on [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh).

**Comment by kddejong** [comment]
I think we need to more research here... there is for sure a difference between what `/w` means between regex implementations. We should comply with the service implementation which will depend on the flags used. For example:
`ŏŏşNÇţā3MKÁŔßïõŜàĆXńńÖÞ` (notice ² removed) is compliant with `^[\w\-.~]+$` in Java with UNICODE_CHARACTER_CLASS flag set.  In python the original string provided is compliant with ^[\w\-.~]+$`  Being able to support unicode characters will be important as those can be allowed by the service.

**Comment by kddejong** [comment]
I may also argue that according to [JSON Schema docs](http://json-schema.org/understanding-json-schema/reference/regular_expressions.html) we shouldn't be allowing regex patterns that use `\w`

**Comment by kddejong** [comment]
For reference this code validates the patterns in the definition: https://github.com/aws-cloudformation/cloudformation-cli/blob/2aad83c68fcd9d5e78520d02c0c89ca8299037e2/src/rpdk/core/data_loaders.py#L245-L254

**Comment by kddejong** [comment]
According to [ECMA 262](https://www.ecma-international.org/publications/standards/Ecma-262.htm),
* \w, \W, \b, \B, \d, \D, \s and \S flags in regex should be ASCII based not unicode
* Unicode is the default in python so we should switch to ASCII (minus the service flipping with a flag)

More details:
https://docs.python.org/3/library/re.html#re.ASCII
https://262.ecma-international.org/5.1/#sec-15.10.2.12
http://json-schema.org/understanding-json-schema/reference/regular_expressions.html
