### ISSUE TITLE
cfn command fails with error

### ISSUE THREAD

**Issue by espriya-az** [aws-cloudformation/cloudformation-cli#900]
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include this information:
Traceback (most recent call last):
  File "/home/$username/.local/lib/python3.7/site-packages/rpdk/core/cli.py", line 83, in main
    init_setup_subparser(subparsers, parents)
  File "/home/$username/.local/lib/python3.7/site-packages/rpdk/core/init.py", line 171, in setup_subparser
    language_setup_subparser()(language_subparsers, [base_subparser])
  File "/home/$username/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2470, in load
    self.require(*args, **kwargs)
  File "/home/$username/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2493, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/$username/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.25.1 (/local/home/$username/.local/lib/python3.7/site-packa
ges), Requirement.parse('requests>=2.26.0'), {'docker'})

**Comment by mmaeng** [comment]
This looks to be a mismatched python package somewhere version.

I would recommend trying to install the requirements again in a python virtual environment.  My usual installation steps tend to be

```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -U pip
$ pip install cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin cloudformation-cli-typescript-plugin
```

Please let us know if that helps!

To get in touch with us, we are also on Discord [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh)

**Comment by espriya-az** [comment]
Hi Michael,

Thanks for your response.  We did not face any error when we ran locally.  We got those errors when we ran in the pipeline.  We are trying to run in beta stage of our pipeline.

Thanks,
Priya

From: "Michael Maeng (AWS)" ***@***.***>
Reply-To: aws-cloudformation/cloudformation-cli ***@***.***>
Date: Thursday, October 20, 2022 at 6:33 PM
To: aws-cloudformation/cloudformation-cli ***@***.***>
Cc: "Ellappan, Shanmuga Priya" ***@***.***>, Author ***@***.***>
Subject: Re: [aws-cloudformation/cloudformation-cli] cfn command fails with error (Issue #900)


This looks to be a mismatched python package somewhere version.

I would recommend trying to install the requirements again in a python virtual environment. My usual installation steps tend to be

$ python3 -m venv .venv

$ source .venv/bin/activate

$ pip install -U pip

$ pip install cloudformation-cli cloudformation-cli-java-plugin cloudformation-cli-go-plugin cloudformation-cli-python-plugin cloudformation-cli-typescript-plugin

Please let us know if that helps!

To get in touch with us, we are also on Discord AWS CloudFormation Discord<https://discord.gg/tmV2gfqh>

**Comment by mmaeng** [comment]
So it looks like you will have to upgrade the requests package on your pipeline box.

`pkg_resources.ContextualVersionConflict: (requests 2.25.1 (/local/home/$username/.local/lib/python3.7/site-packa
ges), Requirement.parse('requests>=2.26.0'), {'docker'})`

So the python docker package is requiring the requests module version to at least be at 2.26.0 and you have 2.25.1 installed.

Hope that helps!

**Comment by mmaeng** [comment]
Please hit us up on [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) if you are still running into issues.  Closing this for now!
