### ISSUE TITLE
Lambda function invoked by CF hook is deployed outside of my AWS environment

### ISSUE THREAD

**Issue by Hiieu** [aws-cloudformation/cloudformation-cli#904]
Hey there 👋 ,

I was going through this guide: https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/hooks.html and I noticed that the lambda function invoked by the cloudformation hook is deployed outside of my AWS environment. 
I've checked this by inspecting the caller identity with `boto3` in the handler:
```
# handler.py
(...)
response = client.get_caller_identity()
print(response)
(...)
```
The response contains an AWS account id that doesn't belong to my organisation. Additionally, the function seems to be deployed in a VPC that is managed somewhere by AWS and it's configured to have access to the Internet - my VPC contains only private subnets. 

Is this done by design? Is it possible to configure the hook to deploy the lambda function inside my VPC?

**Comment by cmgorton** [comment]
Hey @Hiieu. I apologize for the delay in response to this issue. I am going to post this in our internal Slack to see if someone on the team has a good answer for you. Thanks for taking the time to post this question.

**Comment by ericzbeard** [comment]
This is by design. It is not currently possible to run the handler code in your account/vpc. Hooks can be published so that they are available to all AWS users, so they need to be in an account controlled by AWS.

**Comment by otaviomacedo** [comment]
@ericzbeard is it possible to invoke that function directly, despite it being in an account controlled by AWS?

**Comment by ericzbeard** [comment]
No, it's not included with resource type handlers that can be invoked via CCAPI.
