### ISSUE TITLE
getting an error when running cfn command

### ISSUE THREAD

**Issue by madhuakiti** [aws-cloudformation/cloudformation-cli#928]
Hi,

I am getting an error when running cfn submit --set-default command. Please find the below error message for more information and let me know if you have any questions for me.

<img width="1326" alt="Screenshot 2022-10-26 at 3 37 05 PM" src="https://user-images.githubusercontent.com/58709409/198001736-3a5e9366-0075-441a-b354-e4c500c0be72.png">

**Comment by kddejong** [comment]
In your project folder you will have a rpdk.log file. Can you locate the error message in that file and provide it to this issue. Thanks.


Make sure to scrub any private info.

**Comment by madhuakiti** [comment]
The final error message is: 

docker.errors.DockerException" Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'Ni such file or directory'))

FYI: I am guessing this might be a docker deamon issue

**Comment by mmaeng** [comment]
It very well may be a docker issue.  Are you able to run `docker ps` and such?

The bottom chunk of your rpdk.log file containing the error would also be helpful.  Again please remove any private info.

We are also on [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh)!

**Comment by madhuakiti** [comment]
Before the docker related error or exception at the bottom of the log file, there was another error related to file not found inside the hooks folder

**Comment by madhuakiti** [comment]
[rpdk.log](https://github.com/aws-cloudformation/cloudformation-cli/files/9877254/rpdk.log)

**Comment by madhuakiti** [comment]
Yes, those commands are working as expected since the start

FYI: right now I am getting an error related to SSL validation.

**Comment by madhuakiti** [comment]
But still the file not found error is there

**Comment by madhuakiti** [comment]
@mmaeng The SSL issue or error has been resolved now but I am getting a different error. Please find the log file attached for more information.

[rpdk 2.log](https://github.com/aws-cloudformation/cloudformation-cli/files/9887288/rpdk.2.log)

**Comment by mmaeng** [comment]
That looks to be complaining about missing properties in your hooks JSON file.

**Comment by mmaeng** [comment]
Hopefully you were able to resolve your issue with the above.  If not please join us on Discord [AWS CloudFormation Discord](https://discord.gg/tmV2gfqh) or GitHub issue works as well!
