### ISSUE TITLE
Allow specifying --[no-]-use-docker via CLI during packaging / submit

### ISSUE THREAD

**Issue by seawildau** [aws-cloudformation/cloudformation-cli#969]
When building hooks or resources we often want to use a different build configuration on a developers desktop versus in CI. Today I can only specify whether or not builds should happen in a docker container during `cfn init` or by modifying the `.rpdk-config` file, which makes it difficult to configure developers to build using docker on their local machine but have our CI workflow build without docker, as the CI workflow may already be running in a container. I can achieve this today by writing a wrapper that injects different config depending on the build environment, but it would be much easier if I could override the `use_docker` flag at build / packaging time.

Example CLI usage:
```
# Create a new project, setting use_docker to true in the initial config
cfn init

# Validate and package using the project config (build in docker container)
cfn submit --dry-run

# Validate and package without using docker, overriding the project settings, e.g. in a CI container
cfn submit --dry-run --no-use-docker
```

**Comment by mmaeng** [comment]
Thanks for the feedback, will take a look!

**Comment by mmaeng** [comment]
This PR will override the setting for use_docker in .rpdk-config during the `cfn submit` command.  Hope that works for your use case!
