### ISSUE TITLE
=== Unhandled exception === Error got for CFN v2 tests

### ISSUE THREAD

**Issue by maithrp** [aws-cloudformation/cloudformation-cli#972]
Hi Team,

Got the below error using the new handler schema which comes as a part of the ListHandler with input paramters test. 

Explicitly specify value for tagging
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'

[rpdk.log](https://github.com/aws-cloudformation/cloudformation-cli/files/10541532/rpdk.log)

**Comment by AkifRafique** [comment]
please use register-type
